package erpsolaps.erpsolapsmodel.erpsolapseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 31 15:49:02 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtherBillsImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Billid {
            public Object get(OtherBillsImpl obj) {
                return obj.getBillid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBillid((String) value);
            }
        }
        ,
        BillDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getBillDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBillDate((Date) value);
            }
        }
        ,
        Companyid {
            public Object get(OtherBillsImpl obj) {
                return obj.getCompanyid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setCompanyid((String) value);
            }
        }
        ,
        Locationid {
            public Object get(OtherBillsImpl obj) {
                return obj.getLocationid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLocationid((String) value);
            }
        }
        ,
        Deptid {
            public Object get(OtherBillsImpl obj) {
                return obj.getDeptid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setDeptid((String) value);
            }
        }
        ,
        DocTypeId {
            public Object get(OtherBillsImpl obj) {
                return obj.getDocTypeId();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setDocTypeId((String) value);
            }
        }
        ,
        Supplierid {
            public Object get(OtherBillsImpl obj) {
                return obj.getSupplierid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setSupplierid((String) value);
            }
        }
        ,
        Supref {
            public Object get(OtherBillsImpl obj) {
                return obj.getSupref();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setSupref((String) value);
            }
        }
        ,
        SuprefDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getSuprefDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setSuprefDate((Date) value);
            }
        }
        ,
        TaxCode {
            public Object get(OtherBillsImpl obj) {
                return obj.getTaxCode();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setTaxCode((BigDecimal) value);
            }
        }
        ,
        Remarks {
            public Object get(OtherBillsImpl obj) {
                return obj.getRemarks();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setRemarks((String) value);
            }
        }
        ,
        Posted {
            public Object get(OtherBillsImpl obj) {
                return obj.getPosted();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPosted((String) value);
            }
        }
        ,
        Postedby {
            public Object get(OtherBillsImpl obj) {
                return obj.getPostedby();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPostedby((String) value);
            }
        }
        ,
        PostToInterface {
            public Object get(OtherBillsImpl obj) {
                return obj.getPostToInterface();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPostToInterface((String) value);
            }
        }
        ,
        TaxFlag {
            public Object get(OtherBillsImpl obj) {
                return obj.getTaxFlag();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setTaxFlag((String) value);
            }
        }
        ,
        Createdby {
            public Object get(OtherBillsImpl obj) {
                return obj.getCreatedby();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        Modifiedby {
            public Object get(OtherBillsImpl obj) {
                return obj.getModifiedby();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        ApPosted {
            public Object get(OtherBillsImpl obj) {
                return obj.getApPosted();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setApPosted((String) value);
            }
        }
        ,
        GlPosted {
            public Object get(OtherBillsImpl obj) {
                return obj.getGlPosted();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setGlPosted((String) value);
            }
        }
        ,
        AuditorCheck {
            public Object get(OtherBillsImpl obj) {
                return obj.getAuditorCheck();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAuditorCheck((String) value);
            }
        }
        ,
        AuditRemarks {
            public Object get(OtherBillsImpl obj) {
                return obj.getAuditRemarks();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAuditRemarks((String) value);
            }
        }
        ,
        IsMigrated {
            public Object get(OtherBillsImpl obj) {
                return obj.getIsMigrated();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setIsMigrated((String) value);
            }
        }
        ,
        MigratedDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getMigratedDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setMigratedDate((Date) value);
            }
        }
        ,
        ExchangeRate {
            public Object get(OtherBillsImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal) value);
            }
        }
        ,
        LocCurrcode {
            public Object get(OtherBillsImpl obj) {
                return obj.getLocCurrcode();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLocCurrcode((String) value);
            }
        }
        ,
        SalesTaxCode {
            public Object get(OtherBillsImpl obj) {
                return obj.getSalesTaxCode();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setSalesTaxCode((BigDecimal) value);
            }
        }
        ,
        ProjectId {
            public Object get(OtherBillsImpl obj) {
                return obj.getProjectId();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setProjectId((BigDecimal) value);
            }
        }
        ,
        RemarksRescue2 {
            public Object get(OtherBillsImpl obj) {
                return obj.getRemarksRescue2();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setRemarksRescue2((String) value);
            }
        }
        ,
        BillType {
            public Object get(OtherBillsImpl obj) {
                return obj.getBillType();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBillType((String) value);
            }
        }
        ,
        ForwarderSupplierid {
            public Object get(OtherBillsImpl obj) {
                return obj.getForwarderSupplierid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setForwarderSupplierid((String) value);
            }
        }
        ,
        LcCompleteDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getLcCompleteDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLcCompleteDate((Date) value);
            }
        }
        ,
        ImeiFileName {
            public Object get(OtherBillsImpl obj) {
                return obj.getImeiFileName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setImeiFileName((String) value);
            }
        }
        ,
        InvoiceFileName {
            public Object get(OtherBillsImpl obj) {
                return obj.getInvoiceFileName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setInvoiceFileName((String) value);
            }
        }
        ,
        BomFileName {
            public Object get(OtherBillsImpl obj) {
                return obj.getBomFileName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBomFileName((String) value);
            }
        }
        ,
        PackFileName {
            public Object get(OtherBillsImpl obj) {
                return obj.getPackFileName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPackFileName((String) value);
            }
        }
        ,
        LcCompleted {
            public Object get(OtherBillsImpl obj) {
                return obj.getLcCompleted();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLcCompleted((String) value);
            }
        }
        ,
        Poid {
            public Object get(OtherBillsImpl obj) {
                return obj.getPoid();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPoid((String) value);
            }
        }
        ,
        LcForId {
            public Object get(OtherBillsImpl obj) {
                return obj.getLcForId();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLcForId((BigDecimal) value);
            }
        }
        ,
        PalletNo {
            public Object get(OtherBillsImpl obj) {
                return obj.getPalletNo();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPalletNo((BigDecimal) value);
            }
        }
        ,
        CottonQty {
            public Object get(OtherBillsImpl obj) {
                return obj.getCottonQty();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setCottonQty((BigDecimal) value);
            }
        }
        ,
        PoSuppRefDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getPoSuppRefDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPoSuppRefDate((Date) value);
            }
        }
        ,
        PoSuppRefno {
            public Object get(OtherBillsImpl obj) {
                return obj.getPoSuppRefno();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPoSuppRefno((String) value);
            }
        }
        ,
        Potype {
            public Object get(OtherBillsImpl obj) {
                return obj.getPotype();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPotype((String) value);
            }
        }
        ,
        AuditorCheckBy {
            public Object get(OtherBillsImpl obj) {
                return obj.getAuditorCheckBy();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAuditorCheckBy((String) value);
            }
        }
        ,
        AuditorCheckDate {
            public Object get(OtherBillsImpl obj) {
                return obj.getAuditorCheckDate();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAuditorCheckDate((Date) value);
            }
        }
        ,
        AuditorCheckRemarks {
            public Object get(OtherBillsImpl obj) {
                return obj.getAuditorCheckRemarks();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAuditorCheckRemarks((String) value);
            }
        }
        ,
        Lcno {
            public Object get(OtherBillsImpl obj) {
                return obj.getLcno();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setLcno((String) value);
            }
        }
        ,
        Billidseq {
            public Object get(OtherBillsImpl obj) {
                return obj.getBillidseq();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBillidseq((Integer) value);
            }
        }
        ,
        txtLocationName {
            public Object get(OtherBillsImpl obj) {
                return obj.gettxtLocationName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.settxtLocationName((String) value);
            }
        }
        ,
        txtSupplierName {
            public Object get(OtherBillsImpl obj) {
                return obj.gettxtSupplierName();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.settxtSupplierName((String) value);
            }
        }
        ,
        BankRefNo {
            public Object get(OtherBillsImpl obj) {
                return obj.getBankRefNo();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setBankRefNo((String) value);
            }
        }
        ,
        txtErrorMessage {
            public Object get(OtherBillsImpl obj) {
                return obj.gettxtErrorMessage();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.settxtErrorMessage((String) value);
            }
        }
        ,
        OtherBillDet {
            public Object get(OtherBillsImpl obj) {
                return obj.getOtherBillDet();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AllLocations {
            public Object get(OtherBillsImpl obj) {
                return obj.getAllLocations();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAllLocations((EntityImpl) value);
            }
        }
        ,
        PuSuppliers {
            public Object get(OtherBillsImpl obj) {
                return obj.getPuSuppliers();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setPuSuppliers((PuSuppliersImpl) value);
            }
        }
        ,
        AccVwFuncUserBackDateAllowed {
            public Object get(OtherBillsImpl obj) {
                return obj.getAccVwFuncUserBackDateAllowed();
            }

            public void put(OtherBillsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OtherBillsImpl object);

        public abstract void put(OtherBillsImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BILLID = AttributesEnum.Billid.index();
    public static final int BILLDATE = AttributesEnum.BillDate.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int SUPREF = AttributesEnum.Supref.index();
    public static final int SUPREFDATE = AttributesEnum.SuprefDate.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int POSTTOINTERFACE = AttributesEnum.PostToInterface.index();
    public static final int TAXFLAG = AttributesEnum.TaxFlag.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int APPOSTED = AttributesEnum.ApPosted.index();
    public static final int GLPOSTED = AttributesEnum.GlPosted.index();
    public static final int AUDITORCHECK = AttributesEnum.AuditorCheck.index();
    public static final int AUDITREMARKS = AttributesEnum.AuditRemarks.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int SALESTAXCODE = AttributesEnum.SalesTaxCode.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REMARKSRESCUE2 = AttributesEnum.RemarksRescue2.index();
    public static final int BILLTYPE = AttributesEnum.BillType.index();
    public static final int FORWARDERSUPPLIERID = AttributesEnum.ForwarderSupplierid.index();
    public static final int LCCOMPLETEDATE = AttributesEnum.LcCompleteDate.index();
    public static final int IMEIFILENAME = AttributesEnum.ImeiFileName.index();
    public static final int INVOICEFILENAME = AttributesEnum.InvoiceFileName.index();
    public static final int BOMFILENAME = AttributesEnum.BomFileName.index();
    public static final int PACKFILENAME = AttributesEnum.PackFileName.index();
    public static final int LCCOMPLETED = AttributesEnum.LcCompleted.index();
    public static final int POID = AttributesEnum.Poid.index();
    public static final int LCFORID = AttributesEnum.LcForId.index();
    public static final int PALLETNO = AttributesEnum.PalletNo.index();
    public static final int COTTONQTY = AttributesEnum.CottonQty.index();
    public static final int POSUPPREFDATE = AttributesEnum.PoSuppRefDate.index();
    public static final int POSUPPREFNO = AttributesEnum.PoSuppRefno.index();
    public static final int POTYPE = AttributesEnum.Potype.index();
    public static final int AUDITORCHECKBY = AttributesEnum.AuditorCheckBy.index();
    public static final int AUDITORCHECKDATE = AttributesEnum.AuditorCheckDate.index();
    public static final int AUDITORCHECKREMARKS = AttributesEnum.AuditorCheckRemarks.index();
    public static final int LCNO = AttributesEnum.Lcno.index();
    public static final int BILLIDSEQ = AttributesEnum.Billidseq.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int BANKREFNO = AttributesEnum.BankRefNo.index();
    public static final int TXTERRORMESSAGE = AttributesEnum.txtErrorMessage.index();
    public static final int OTHERBILLDET = AttributesEnum.OtherBillDet.index();
    public static final int ALLLOCATIONS = AttributesEnum.AllLocations.index();
    public static final int PUSUPPLIERS = AttributesEnum.PuSuppliers.index();
    public static final int ACCVWFUNCUSERBACKDATEALLOWED = AttributesEnum.AccVwFuncUserBackDateAllowed.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OtherBillsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolaps.erpsolapsmodel.erpsolapseo.OtherBills");
    }


    /**
     * Gets the attribute value for Billid, using the alias name Billid.
     * @return the value of Billid
     */
    public String getBillid() {
        return (String) getAttributeInternal(BILLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Billid.
     * @param value value to set the Billid
     */
    public void setBillid(String value) {
        setAttributeInternal(BILLID, value);
    }

    /**
     * Gets the attribute value for BillDate, using the alias name BillDate.
     * @return the value of BillDate
     */
    public Date getBillDate() {
        return (Date) getAttributeInternal(BILLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillDate.
     * @param value value to set the BillDate
     */
    public void setBillDate(Date value) {
        setAttributeInternal(BILLDATE, value);
    }

    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Deptid, using the alias name Deptid.
     * @return the value of Deptid
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deptid.
     * @param value value to set the Deptid
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for DocTypeId, using the alias name DocTypeId.
     * @return the value of DocTypeId
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocTypeId.
     * @param value value to set the DocTypeId
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for Supplierid, using the alias name Supplierid.
     * @return the value of Supplierid
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierid.
     * @param value value to set the Supplierid
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for Supref, using the alias name Supref.
     * @return the value of Supref
     */
    public String getSupref() {
        return (String) getAttributeInternal(SUPREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supref.
     * @param value value to set the Supref
     */
    public void setSupref(String value) {
        setAttributeInternal(SUPREF, value);
    }

    /**
     * Gets the attribute value for SuprefDate, using the alias name SuprefDate.
     * @return the value of SuprefDate
     */
    public Date getSuprefDate() {
        return (Date) getAttributeInternal(SUPREFDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuprefDate.
     * @param value value to set the SuprefDate
     */
    public void setSuprefDate(Date value) {
        setAttributeInternal(SUPREFDATE, value);
    }

    /**
     * Gets the attribute value for TaxCode, using the alias name TaxCode.
     * @return the value of TaxCode
     */
    public BigDecimal getTaxCode() {
        return (BigDecimal) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxCode.
     * @param value value to set the TaxCode
     */
    public void setTaxCode(BigDecimal value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Postedby, using the alias name Postedby.
     * @return the value of Postedby
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postedby.
     * @param value value to set the Postedby
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for PostToInterface, using the alias name PostToInterface.
     * @return the value of PostToInterface
     */
    public String getPostToInterface() {
        return (String) getAttributeInternal(POSTTOINTERFACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostToInterface.
     * @param value value to set the PostToInterface
     */
    public void setPostToInterface(String value) {
        setAttributeInternal(POSTTOINTERFACE, value);
    }

    /**
     * Gets the attribute value for TaxFlag, using the alias name TaxFlag.
     * @return the value of TaxFlag
     */
    public String getTaxFlag() {
        return (String) getAttributeInternal(TAXFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxFlag.
     * @param value value to set the TaxFlag
     */
    public void setTaxFlag(String value) {
        setAttributeInternal(TAXFLAG, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ApPosted, using the alias name ApPosted.
     * @return the value of ApPosted
     */
    public String getApPosted() {
        return (String) getAttributeInternal(APPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApPosted.
     * @param value value to set the ApPosted
     */
    public void setApPosted(String value) {
        setAttributeInternal(APPOSTED, value);
    }

    /**
     * Gets the attribute value for GlPosted, using the alias name GlPosted.
     * @return the value of GlPosted
     */
    public String getGlPosted() {
        return (String) getAttributeInternal(GLPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlPosted.
     * @param value value to set the GlPosted
     */
    public void setGlPosted(String value) {
        setAttributeInternal(GLPOSTED, value);
    }

    /**
     * Gets the attribute value for AuditorCheck, using the alias name AuditorCheck.
     * @return the value of AuditorCheck
     */
    public String getAuditorCheck() {
        return (String) getAttributeInternal(AUDITORCHECK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheck.
     * @param value value to set the AuditorCheck
     */
    public void setAuditorCheck(String value) {
        setAttributeInternal(AUDITORCHECK, value);
    }

    /**
     * Gets the attribute value for AuditRemarks, using the alias name AuditRemarks.
     * @return the value of AuditRemarks
     */
    public String getAuditRemarks() {
        return (String) getAttributeInternal(AUDITREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditRemarks.
     * @param value value to set the AuditRemarks
     */
    public void setAuditRemarks(String value) {
        setAttributeInternal(AUDITREMARKS, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the value of ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for LocCurrcode, using the alias name LocCurrcode.
     * @return the value of LocCurrcode
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocCurrcode.
     * @param value value to set the LocCurrcode
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for SalesTaxCode, using the alias name SalesTaxCode.
     * @return the value of SalesTaxCode
     */
    public BigDecimal getSalesTaxCode() {
        return (BigDecimal) getAttributeInternal(SALESTAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesTaxCode.
     * @param value value to set the SalesTaxCode
     */
    public void setSalesTaxCode(BigDecimal value) {
        setAttributeInternal(SALESTAXCODE, value);
    }

    /**
     * Gets the attribute value for ProjectId, using the alias name ProjectId.
     * @return the value of ProjectId
     */
    public BigDecimal getProjectId() {
        return (BigDecimal) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectId.
     * @param value value to set the ProjectId
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for RemarksRescue2, using the alias name RemarksRescue2.
     * @return the value of RemarksRescue2
     */
    public String getRemarksRescue2() {
        return (String) getAttributeInternal(REMARKSRESCUE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemarksRescue2.
     * @param value value to set the RemarksRescue2
     */
    public void setRemarksRescue2(String value) {
        setAttributeInternal(REMARKSRESCUE2, value);
    }

    /**
     * Gets the attribute value for BillType, using the alias name BillType.
     * @return the value of BillType
     */
    public String getBillType() {
        return (String) getAttributeInternal(BILLTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillType.
     * @param value value to set the BillType
     */
    public void setBillType(String value) {
        setAttributeInternal(BILLTYPE, value);
    }

    /**
     * Gets the attribute value for ForwarderSupplierid, using the alias name ForwarderSupplierid.
     * @return the value of ForwarderSupplierid
     */
    public String getForwarderSupplierid() {
        return (String) getAttributeInternal(FORWARDERSUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ForwarderSupplierid.
     * @param value value to set the ForwarderSupplierid
     */
    public void setForwarderSupplierid(String value) {
        setAttributeInternal(FORWARDERSUPPLIERID, value);
    }

    /**
     * Gets the attribute value for LcCompleteDate, using the alias name LcCompleteDate.
     * @return the value of LcCompleteDate
     */
    public Date getLcCompleteDate() {
        return (Date) getAttributeInternal(LCCOMPLETEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcCompleteDate.
     * @param value value to set the LcCompleteDate
     */
    public void setLcCompleteDate(Date value) {
        setAttributeInternal(LCCOMPLETEDATE, value);
    }

    /**
     * Gets the attribute value for ImeiFileName, using the alias name ImeiFileName.
     * @return the value of ImeiFileName
     */
    public String getImeiFileName() {
        return (String) getAttributeInternal(IMEIFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImeiFileName.
     * @param value value to set the ImeiFileName
     */
    public void setImeiFileName(String value) {
        setAttributeInternal(IMEIFILENAME, value);
    }

    /**
     * Gets the attribute value for InvoiceFileName, using the alias name InvoiceFileName.
     * @return the value of InvoiceFileName
     */
    public String getInvoiceFileName() {
        return (String) getAttributeInternal(INVOICEFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceFileName.
     * @param value value to set the InvoiceFileName
     */
    public void setInvoiceFileName(String value) {
        setAttributeInternal(INVOICEFILENAME, value);
    }

    /**
     * Gets the attribute value for BomFileName, using the alias name BomFileName.
     * @return the value of BomFileName
     */
    public String getBomFileName() {
        return (String) getAttributeInternal(BOMFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomFileName.
     * @param value value to set the BomFileName
     */
    public void setBomFileName(String value) {
        setAttributeInternal(BOMFILENAME, value);
    }

    /**
     * Gets the attribute value for PackFileName, using the alias name PackFileName.
     * @return the value of PackFileName
     */
    public String getPackFileName() {
        return (String) getAttributeInternal(PACKFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackFileName.
     * @param value value to set the PackFileName
     */
    public void setPackFileName(String value) {
        setAttributeInternal(PACKFILENAME, value);
    }

    /**
     * Gets the attribute value for LcCompleted, using the alias name LcCompleted.
     * @return the value of LcCompleted
     */
    public String getLcCompleted() {
        return (String) getAttributeInternal(LCCOMPLETED);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcCompleted.
     * @param value value to set the LcCompleted
     */
    public void setLcCompleted(String value) {
        setAttributeInternal(LCCOMPLETED, value);
    }

    /**
     * Gets the attribute value for Poid, using the alias name Poid.
     * @return the value of Poid
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poid.
     * @param value value to set the Poid
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for LcForId, using the alias name LcForId.
     * @return the value of LcForId
     */
    public BigDecimal getLcForId() {
        return (BigDecimal) getAttributeInternal(LCFORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcForId.
     * @param value value to set the LcForId
     */
    public void setLcForId(BigDecimal value) {
        setAttributeInternal(LCFORID, value);
    }

    /**
     * Gets the attribute value for PalletNo, using the alias name PalletNo.
     * @return the value of PalletNo
     */
    public BigDecimal getPalletNo() {
        return (BigDecimal) getAttributeInternal(PALLETNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PalletNo.
     * @param value value to set the PalletNo
     */
    public void setPalletNo(BigDecimal value) {
        setAttributeInternal(PALLETNO, value);
    }

    /**
     * Gets the attribute value for CottonQty, using the alias name CottonQty.
     * @return the value of CottonQty
     */
    public BigDecimal getCottonQty() {
        return (BigDecimal) getAttributeInternal(COTTONQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CottonQty.
     * @param value value to set the CottonQty
     */
    public void setCottonQty(BigDecimal value) {
        setAttributeInternal(COTTONQTY, value);
    }

    /**
     * Gets the attribute value for PoSuppRefDate, using the alias name PoSuppRefDate.
     * @return the value of PoSuppRefDate
     */
    public Date getPoSuppRefDate() {
        return (Date) getAttributeInternal(POSUPPREFDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoSuppRefDate.
     * @param value value to set the PoSuppRefDate
     */
    public void setPoSuppRefDate(Date value) {
        setAttributeInternal(POSUPPREFDATE, value);
    }

    /**
     * Gets the attribute value for PoSuppRefno, using the alias name PoSuppRefno.
     * @return the value of PoSuppRefno
     */
    public String getPoSuppRefno() {
        return (String) getAttributeInternal(POSUPPREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoSuppRefno.
     * @param value value to set the PoSuppRefno
     */
    public void setPoSuppRefno(String value) {
        setAttributeInternal(POSUPPREFNO, value);
    }

    /**
     * Gets the attribute value for Potype, using the alias name Potype.
     * @return the value of Potype
     */
    public String getPotype() {
        return (String) getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Potype.
     * @param value value to set the Potype
     */
    public void setPotype(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for AuditorCheckBy, using the alias name AuditorCheckBy.
     * @return the value of AuditorCheckBy
     */
    public String getAuditorCheckBy() {
        return (String) getAttributeInternal(AUDITORCHECKBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckBy.
     * @param value value to set the AuditorCheckBy
     */
    public void setAuditorCheckBy(String value) {
        setAttributeInternal(AUDITORCHECKBY, value);
    }

    /**
     * Gets the attribute value for AuditorCheckDate, using the alias name AuditorCheckDate.
     * @return the value of AuditorCheckDate
     */
    public Date getAuditorCheckDate() {
        return (Date) getAttributeInternal(AUDITORCHECKDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckDate.
     * @param value value to set the AuditorCheckDate
     */
    public void setAuditorCheckDate(Date value) {
        setAttributeInternal(AUDITORCHECKDATE, value);
    }

    /**
     * Gets the attribute value for AuditorCheckRemarks, using the alias name AuditorCheckRemarks.
     * @return the value of AuditorCheckRemarks
     */
    public String getAuditorCheckRemarks() {
        return (String) getAttributeInternal(AUDITORCHECKREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckRemarks.
     * @param value value to set the AuditorCheckRemarks
     */
    public void setAuditorCheckRemarks(String value) {
        setAttributeInternal(AUDITORCHECKREMARKS, value);
    }

    /**
     * Gets the attribute value for Lcno, using the alias name Lcno.
     * @return the value of Lcno
     */
    public String getLcno() {
        return (String) getAttributeInternal(LCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lcno.
     * @param value value to set the Lcno
     */
    public void setLcno(String value) {
        setAttributeInternal(LCNO, value);
    }

    /**
     * Gets the attribute value for Billidseq, using the alias name Billidseq.
     * @return the value of Billidseq
     */
    public Integer getBillidseq() {
        return (Integer) getAttributeInternal(BILLIDSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Billidseq.
     * @param value value to set the Billidseq
     */
    public void setBillidseq(Integer value) {
        setAttributeInternal(BILLIDSEQ, value);
    }

    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for txtSupplierName, using the alias name txtSupplierName.
     * @return the value of txtSupplierName
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSupplierName.
     * @param value value to set the txtSupplierName
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for BankRefNo, using the alias name BankRefNo.
     * @return the value of BankRefNo
     */
    public String getBankRefNo() {
        return (String) getAttributeInternal(BANKREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankRefNo.
     * @param value value to set the BankRefNo
     */
    public void setBankRefNo(String value) {
        setAttributeInternal(BANKREFNO, value==null?null:value.toUpperCase());
    }

    /**
     * Gets the attribute value for txtErrorMessage, using the alias name txtErrorMessage.
     * @return the value of txtErrorMessage
     */
    public String gettxtErrorMessage() {
        return (String) getAttributeInternal(TXTERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtErrorMessage.
     * @param value value to set the txtErrorMessage
     */
    public void settxtErrorMessage(String value) {
        setAttributeInternal(TXTERRORMESSAGE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOtherBillDet() {
        return (RowIterator) getAttributeInternal(OTHERBILLDET);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllLocations() {
        return (EntityImpl) getAttributeInternal(ALLLOCATIONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllLocations(EntityImpl value) {
        setAttributeInternal(ALLLOCATIONS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public PuSuppliersImpl getPuSuppliers() {
        return (PuSuppliersImpl) getAttributeInternal(PUSUPPLIERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPuSuppliers(PuSuppliersImpl value) {
        setAttributeInternal(PUSUPPLIERS, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncUserBackDateAllowed.
     */
    public RowSet getAccVwFuncUserBackDateAllowed() {
        return (RowSet) getAttributeInternal(ACCVWFUNCUSERBACKDATEALLOWED);
    }


    /**
     * @param billidseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer billidseq) {
        return new Key(new Object[] { billidseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Billidseq");
        setERPSolPKSeqName("OTHER_BILLS_SEQ");
        setCompanyid(ERPSolGlobClassModel.doGetUserCompanyCode());
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation==DML_INSERT) {
            ;
           String pkValue =
                " bill_id('" + ERPSolGlobClassModel.doGetUserCompanyCode() + "','" +
                ERPSolGlobClassModel.doGetUserLocationCode() + "','B',TO_DATE('" + getBillDate() + "','YYYY-MM-DD'))";
            System.out.println(pkValue + "pk value");
            String result =
                ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(BILLID, result);            

        }
        super.doDML(operation, e);
    }
    
    @Override
    public void afterCommit(TransactionEvent transactionEvent) {
        // TODO Implement this method
        System.out.println("committing-1");
        if (getPosted().equals("Y")) {
           super.afterCommit(transactionEvent);
           return;
        }
            CallableStatement cs=this.getDBTransaction().createCallableStatement("begin  PKG_GENERATE_ACCOUNTING.GV_POST_TO_INTERFACE:='N'; PKG_GENERATE_ACCOUNTING.PROC_GENERATE_OTHER_BILLS_ACCT('"+getBillid()+"'); commit;  PKG_GENERATE_ACCOUNTING.GV_POST_TO_INTERFACE:='Y'; END;", 1);
            System.out.println("begin PKG_GENERATE_ACCOUNTING.PROC_GENERATE_OTHER_BILLS_ACCT('"+getBillid()+"'); commit; END;");
            try {
                cs.executeUpdate();
            } catch (SQLException e) {
        //            this.getCurrentRow().setAttribute("Submit", "N");
            JboException ex=new JboException(e.getMessage());
            ex.setSeverity(JboException.SEVERITY_WARNING);
            throw ex;
                
    //                System.out.println(e.getMessage()+ "this is message");
    //                throw new JboException("Unable to supervise ");
            }
            finally{
                try {
                    cs.close();
                } catch (SQLException e) {
                }
            }
        
        super.afterCommit(transactionEvent);
    }
}

