package erpsolaps.erpsolapsmodel.erpsolapseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 31 15:49:26 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtherBillDetImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Billid {
            public Object get(OtherBillDetImpl obj) {
                return obj.getBillid();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setBillid((String) value);
            }
        }
        ,
        Glcode {
            public Object get(OtherBillDetImpl obj) {
                return obj.getGlcode();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setGlcode((String) value);
            }
        }
        ,
        Costcenter {
            public Object get(OtherBillDetImpl obj) {
                return obj.getCostcenter();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setCostcenter((String) value);
            }
        }
        ,
        Amount {
            public Object get(OtherBillDetImpl obj) {
                return obj.getAmount();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setAmount((BigDecimal) value);
            }
        }
        ,
        GlNarr {
            public Object get(OtherBillDetImpl obj) {
                return obj.getGlNarr();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setGlNarr((String) value);
            }
        }
        ,
        Createdby {
            public Object get(OtherBillDetImpl obj) {
                return obj.getCreatedby();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(OtherBillDetImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        Modifiedby {
            public Object get(OtherBillDetImpl obj) {
                return obj.getModifiedby();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(OtherBillDetImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        Seqid {
            public Object get(OtherBillDetImpl obj) {
                return obj.getSeqid();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setSeqid((Integer) value);
            }
        }
        ,
        LocCode {
            public Object get(OtherBillDetImpl obj) {
                return obj.getLocCode();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setLocCode((String) value);
            }
        }
        ,
        FcurrAmount {
            public Object get(OtherBillDetImpl obj) {
                return obj.getFcurrAmount();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setFcurrAmount((BigDecimal) value);
            }
        }
        ,
        FcurrStAmount {
            public Object get(OtherBillDetImpl obj) {
                return obj.getFcurrStAmount();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setFcurrStAmount((BigDecimal) value);
            }
        }
        ,
        StAmount {
            public Object get(OtherBillDetImpl obj) {
                return obj.getStAmount();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setStAmount((BigDecimal) value);
            }
        }
        ,
        GlNarrRescue2 {
            public Object get(OtherBillDetImpl obj) {
                return obj.getGlNarrRescue2();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setGlNarrRescue2((String) value);
            }
        }
        ,
        Itemid {
            public Object get(OtherBillDetImpl obj) {
                return obj.getItemid();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setItemid((String) value);
            }
        }
        ,
        OrderQty {
            public Object get(OtherBillDetImpl obj) {
                return obj.getOrderQty();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setOrderQty((BigDecimal) value);
            }
        }
        ,
        ExtraQty {
            public Object get(OtherBillDetImpl obj) {
                return obj.getExtraQty();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setExtraQty((BigDecimal) value);
            }
        }
        ,
        FcurRate {
            public Object get(OtherBillDetImpl obj) {
                return obj.getFcurRate();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setFcurRate((BigDecimal) value);
            }
        }
        ,
        BcurRate {
            public Object get(OtherBillDetImpl obj) {
                return obj.getBcurRate();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setBcurRate((BigDecimal) value);
            }
        }
        ,
        FcurrTotal {
            public Object get(OtherBillDetImpl obj) {
                return obj.getFcurrTotal();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setFcurrTotal((BigDecimal) value);
            }
        }
        ,
        BcurrTotal {
            public Object get(OtherBillDetImpl obj) {
                return obj.getBcurrTotal();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setBcurrTotal((BigDecimal) value);
            }
        }
        ,
        MemoBillid {
            public Object get(OtherBillDetImpl obj) {
                return obj.getMemoBillid();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setMemoBillid((String) value);
            }
        }
        ,
        ExchangeRate {
            public Object get(OtherBillDetImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal) value);
            }
        }
        ,
        PoAmount {
            public Object get(OtherBillDetImpl obj) {
                return obj.getPoAmount();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setPoAmount((BigDecimal) value);
            }
        }
        ,
        Billidseq {
            public Object get(OtherBillDetImpl obj) {
                return obj.getBillidseq();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setBillidseq((Integer) value);
            }
        }
        ,
        OtherBills {
            public Object get(OtherBillDetImpl obj) {
                return obj.getOtherBills();
            }

            public void put(OtherBillDetImpl obj, Object value) {
                obj.setOtherBills((OtherBillsImpl) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OtherBillDetImpl object);

        public abstract void put(OtherBillDetImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BILLID = AttributesEnum.Billid.index();
    public static final int GLCODE = AttributesEnum.Glcode.index();
    public static final int COSTCENTER = AttributesEnum.Costcenter.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int GLNARR = AttributesEnum.GlNarr.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int SEQID = AttributesEnum.Seqid.index();
    public static final int LOCCODE = AttributesEnum.LocCode.index();
    public static final int FCURRAMOUNT = AttributesEnum.FcurrAmount.index();
    public static final int FCURRSTAMOUNT = AttributesEnum.FcurrStAmount.index();
    public static final int STAMOUNT = AttributesEnum.StAmount.index();
    public static final int GLNARRRESCUE2 = AttributesEnum.GlNarrRescue2.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int EXTRAQTY = AttributesEnum.ExtraQty.index();
    public static final int FCURRATE = AttributesEnum.FcurRate.index();
    public static final int BCURRATE = AttributesEnum.BcurRate.index();
    public static final int FCURRTOTAL = AttributesEnum.FcurrTotal.index();
    public static final int BCURRTOTAL = AttributesEnum.BcurrTotal.index();
    public static final int MEMOBILLID = AttributesEnum.MemoBillid.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int POAMOUNT = AttributesEnum.PoAmount.index();
    public static final int BILLIDSEQ = AttributesEnum.Billidseq.index();
    public static final int OTHERBILLS = AttributesEnum.OtherBills.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OtherBillDetImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolaps.erpsolapsmodel.erpsolapseo.OtherBillDet");
    }


    /**
     * Gets the attribute value for Billid, using the alias name Billid.
     * @return the value of Billid
     */
    public String getBillid() {
        return (String) getAttributeInternal(BILLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Billid.
     * @param value value to set the Billid
     */
    public void setBillid(String value) {
        setAttributeInternal(BILLID, value);
    }

    /**
     * Gets the attribute value for Glcode, using the alias name Glcode.
     * @return the value of Glcode
     */
    public String getGlcode() {
        return (String) getAttributeInternal(GLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Glcode.
     * @param value value to set the Glcode
     */
    public void setGlcode(String value) {
        setAttributeInternal(GLCODE, value);
    }

    /**
     * Gets the attribute value for Costcenter, using the alias name Costcenter.
     * @return the value of Costcenter
     */
    public String getCostcenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Costcenter.
     * @param value value to set the Costcenter
     */
    public void setCostcenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for GlNarr, using the alias name GlNarr.
     * @return the value of GlNarr
     */
    public String getGlNarr() {
        return (String) getAttributeInternal(GLNARR);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlNarr.
     * @param value value to set the GlNarr
     */
    public void setGlNarr(String value) {
        setAttributeInternal(GLNARR, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Seqid, using the alias name Seqid.
     * @return the value of Seqid
     */
    public Integer getSeqid() {
        return (Integer) getAttributeInternal(SEQID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Seqid.
     * @param value value to set the Seqid
     */
    public void setSeqid(Integer value) {
        setAttributeInternal(SEQID, value);
    }

    /**
     * Gets the attribute value for LocCode, using the alias name LocCode.
     * @return the value of LocCode
     */
    public String getLocCode() {
        return (String) getAttributeInternal(LOCCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocCode.
     * @param value value to set the LocCode
     */
    public void setLocCode(String value) {
        setAttributeInternal(LOCCODE, value);
    }

    /**
     * Gets the attribute value for FcurrAmount, using the alias name FcurrAmount.
     * @return the value of FcurrAmount
     */
    public BigDecimal getFcurrAmount() {
        return (BigDecimal) getAttributeInternal(FCURRAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrAmount.
     * @param value value to set the FcurrAmount
     */
    public void setFcurrAmount(BigDecimal value) {
        setAttributeInternal(FCURRAMOUNT, value);
    }

    /**
     * Gets the attribute value for FcurrStAmount, using the alias name FcurrStAmount.
     * @return the value of FcurrStAmount
     */
    public BigDecimal getFcurrStAmount() {
        return (BigDecimal) getAttributeInternal(FCURRSTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrStAmount.
     * @param value value to set the FcurrStAmount
     */
    public void setFcurrStAmount(BigDecimal value) {
        setAttributeInternal(FCURRSTAMOUNT, value);
    }

    /**
     * Gets the attribute value for StAmount, using the alias name StAmount.
     * @return the value of StAmount
     */
    public BigDecimal getStAmount() {
        return (BigDecimal) getAttributeInternal(STAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StAmount.
     * @param value value to set the StAmount
     */
    public void setStAmount(BigDecimal value) {
        setAttributeInternal(STAMOUNT, value);
    }

    /**
     * Gets the attribute value for GlNarrRescue2, using the alias name GlNarrRescue2.
     * @return the value of GlNarrRescue2
     */
    public String getGlNarrRescue2() {
        return (String) getAttributeInternal(GLNARRRESCUE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlNarrRescue2.
     * @param value value to set the GlNarrRescue2
     */
    public void setGlNarrRescue2(String value) {
        setAttributeInternal(GLNARRRESCUE2, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the value of OrderQty
     */
    public BigDecimal getOrderQty() {
        return (BigDecimal) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(BigDecimal value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for ExtraQty, using the alias name ExtraQty.
     * @return the value of ExtraQty
     */
    public BigDecimal getExtraQty() {
        return (BigDecimal) getAttributeInternal(EXTRAQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraQty.
     * @param value value to set the ExtraQty
     */
    public void setExtraQty(BigDecimal value) {
        setAttributeInternal(EXTRAQTY, value);
    }

    /**
     * Gets the attribute value for FcurRate, using the alias name FcurRate.
     * @return the value of FcurRate
     */
    public BigDecimal getFcurRate() {
        return (BigDecimal) getAttributeInternal(FCURRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurRate.
     * @param value value to set the FcurRate
     */
    public void setFcurRate(BigDecimal value) {
        setAttributeInternal(FCURRATE, value);
    }

    /**
     * Gets the attribute value for BcurRate, using the alias name BcurRate.
     * @return the value of BcurRate
     */
    public BigDecimal getBcurRate() {
        return (BigDecimal) getAttributeInternal(BCURRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BcurRate.
     * @param value value to set the BcurRate
     */
    public void setBcurRate(BigDecimal value) {
        setAttributeInternal(BCURRATE, value);
    }

    /**
     * Gets the attribute value for FcurrTotal, using the alias name FcurrTotal.
     * @return the value of FcurrTotal
     */
    public BigDecimal getFcurrTotal() {
        return (BigDecimal) getAttributeInternal(FCURRTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrTotal.
     * @param value value to set the FcurrTotal
     */
    public void setFcurrTotal(BigDecimal value) {
        setAttributeInternal(FCURRTOTAL, value);
    }

    /**
     * Gets the attribute value for BcurrTotal, using the alias name BcurrTotal.
     * @return the value of BcurrTotal
     */
    public BigDecimal getBcurrTotal() {
        return (BigDecimal) getAttributeInternal(BCURRTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for BcurrTotal.
     * @param value value to set the BcurrTotal
     */
    public void setBcurrTotal(BigDecimal value) {
        setAttributeInternal(BCURRTOTAL, value);
    }

    /**
     * Gets the attribute value for MemoBillid, using the alias name MemoBillid.
     * @return the value of MemoBillid
     */
    public String getMemoBillid() {
        return (String) getAttributeInternal(MEMOBILLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MemoBillid.
     * @param value value to set the MemoBillid
     */
    public void setMemoBillid(String value) {
        setAttributeInternal(MEMOBILLID, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the value of ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for PoAmount, using the alias name PoAmount.
     * @return the value of PoAmount
     */
    public BigDecimal getPoAmount() {
        return (BigDecimal) getAttributeInternal(POAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoAmount.
     * @param value value to set the PoAmount
     */
    public void setPoAmount(BigDecimal value) {
        setAttributeInternal(POAMOUNT, value);
    }


    /**
     * Gets the attribute value for Billidseq, using the alias name Billidseq.
     * @return the value of Billidseq
     */
    public Integer getBillidseq() {
        return (Integer) getAttributeInternal(BILLIDSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Billidseq.
     * @param value value to set the Billidseq
     */
    public void setBillidseq(Integer value) {
        setAttributeInternal(BILLIDSEQ, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity OtherBillsImpl.
     */
    public OtherBillsImpl getOtherBills() {
        return (OtherBillsImpl) getAttributeInternal(OTHERBILLS);
    }

    /**
     * Sets <code>value</code> as the associated entity OtherBillsImpl.
     */
    public void setOtherBills(OtherBillsImpl value) {
        setAttributeInternal(OTHERBILLS, value);
    }


    /**
     * @param seqid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer seqid) {
        return new Key(new Object[] { seqid });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Seqid");
        setERPSolPKSeqName("OTHER_BILL_DET_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            populateAttributeAsChanged(BILLID, getOtherBills().getAttribute("Billid"));
       }
        if (operation!=DML_DELETE) {
           populateAttributeAsChanged(AMOUNT, getFcurrAmount());
           populateAttributeAsChanged(STAMOUNT, getFcurrStAmount());
       }
        super.doDML(operation, e);
    }
}

