package erpsolaps.erpsolapsmodel.erpsolapseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 06 16:06:18 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaymentMasterImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PaymentCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentCode((String) value);
            }
        }
        ,
        DocTypeId {
            public Object get(PaymentMasterImpl obj) {
                return obj.getDocTypeId();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setDocTypeId((String) value);
            }
        }
        ,
        InvoiceCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getInvoiceCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setInvoiceCode((String) value);
            }
        }
        ,
        PaymentMode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentMode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentMode((String) value);
            }
        }
        ,
        PaymentType {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentType();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentType((String) value);
            }
        }
        ,
        Supplierid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getSupplierid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setSupplierid((String) value);
            }
        }
        ,
        PaymentAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentAmount((BigDecimal) value);
            }
        }
        ,
        PaymentDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentDate((Date) value);
            }
        }
        ,
        RefVoucherNo {
            public Object get(PaymentMasterImpl obj) {
                return obj.getRefVoucherNo();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setRefVoucherNo((String) value);
            }
        }
        ,
        Submit {
            public Object get(PaymentMasterImpl obj) {
                return obj.getSubmit();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setSubmit((String) value);
            }
        }
        ,
        Createdby {
            public Object get(PaymentMasterImpl obj) {
                return obj.getCreatedby();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        Modifiedby {
            public Object get(PaymentMasterImpl obj) {
                return obj.getModifiedby();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        PostToIntFace {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPostToIntFace();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPostToIntFace((String) value);
            }
        }
        ,
        PostToGl {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPostToGl();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPostToGl((String) value);
            }
        }
        ,
        Companyid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getCompanyid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setCompanyid((String) value);
            }
        }
        ,
        Locationid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getLocationid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setLocationid((String) value);
            }
        }
        ,
        Deptid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getDeptid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setDeptid((String) value);
            }
        }
        ,
        ChequeNo {
            public Object get(PaymentMasterImpl obj) {
                return obj.getChequeNo();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setChequeNo((String) value);
            }
        }
        ,
        ChequeDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getChequeDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setChequeDate((Date) value);
            }
        }
        ,
        Bankid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getBankid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setBankid((String) value);
            }
        }
        ,
        Branchid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getBranchid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setBranchid((String) value);
            }
        }
        ,
        TaxPaid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getTaxPaid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setTaxPaid((String) value);
            }
        }
        ,
        ApPosted {
            public Object get(PaymentMasterImpl obj) {
                return obj.getApPosted();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setApPosted((String) value);
            }
        }
        ,
        Bookid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getBookid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setBookid((String) value);
            }
        }
        ,
        AdtaxCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAdtaxCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAdtaxCode((BigDecimal) value);
            }
        }
        ,
        TaxAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getTaxAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setTaxAmount((BigDecimal) value);
            }
        }
        ,
        LocalFlag {
            public Object get(PaymentMasterImpl obj) {
                return obj.getLocalFlag();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setLocalFlag((String) value);
            }
        }
        ,
        IbdocTypeId {
            public Object get(PaymentMasterImpl obj) {
                return obj.getIbdocTypeId();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setIbdocTypeId((String) value);
            }
        }
        ,
        BankLocid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getBankLocid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setBankLocid((String) value);
            }
        }
        ,
        Narration {
            public Object get(PaymentMasterImpl obj) {
                return obj.getNarration();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setNarration((String) value);
            }
        }
        ,
        PermanetId {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPermanetId();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPermanetId((String) value);
            }
        }
        ,
        SubmitDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getSubmitDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setSubmitDate((Date) value);
            }
        }
        ,
        PayeeName {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPayeeName();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPayeeName((String) value);
            }
        }
        ,
        AuditorCheck {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAuditorCheck();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAuditorCheck((String) value);
            }
        }
        ,
        AuditRemarks {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAuditRemarks();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAuditRemarks((String) value);
            }
        }
        ,
        IsMigrated {
            public Object get(PaymentMasterImpl obj) {
                return obj.getIsMigrated();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setIsMigrated((String) value);
            }
        }
        ,
        MigratedDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getMigratedDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setMigratedDate((Date) value);
            }
        }
        ,
        Postedby {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPostedby();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPostedby((String) value);
            }
        }
        ,
        ExchangeRate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal) value);
            }
        }
        ,
        LocCurrcode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getLocCurrcode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setLocCurrcode((String) value);
            }
        }
        ,
        FcurrPayAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getFcurrPayAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setFcurrPayAmount((BigDecimal) value);
            }
        }
        ,
        FcurrTaxAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getFcurrTaxAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setFcurrTaxAmount((BigDecimal) value);
            }
        }
        ,
        NarrationRescue2 {
            public Object get(PaymentMasterImpl obj) {
                return obj.getNarrationRescue2();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setNarrationRescue2((String) value);
            }
        }
        ,
        RefDoctypeid {
            public Object get(PaymentMasterImpl obj) {
                return obj.getRefDoctypeid();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setRefDoctypeid((String) value);
            }
        }
        ,
        RefDocumentId {
            public Object get(PaymentMasterImpl obj) {
                return obj.getRefDocumentId();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setRefDocumentId((String) value);
            }
        }
        ,
        OtfEx {
            public Object get(PaymentMasterImpl obj) {
                return obj.getOtfEx();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setOtfEx((String) value);
            }
        }
        ,
        ApprovedMemoId {
            public Object get(PaymentMasterImpl obj) {
                return obj.getApprovedMemoId();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setApprovedMemoId((String) value);
            }
        }
        ,
        AuditorCheckBy {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAuditorCheckBy();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAuditorCheckBy((String) value);
            }
        }
        ,
        AuditorCheckDate {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAuditorCheckDate();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAuditorCheckDate((Date) value);
            }
        }
        ,
        AuditorCheckRemarks {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAuditorCheckRemarks();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAuditorCheckRemarks((String) value);
            }
        }
        ,
        FcurrStaxAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getFcurrStaxAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setFcurrStaxAmount((BigDecimal) value);
            }
        }
        ,
        StaxAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.getStaxAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setStaxAmount((BigDecimal) value);
            }
        }
        ,
        AdsalesTaxCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAdsalesTaxCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAdsalesTaxCode((BigDecimal) value);
            }
        }
        ,
        Paymentseq {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentseq();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPaymentseq((Integer) value);
            }
        }
        ,
        txtLocationName {
            public Object get(PaymentMasterImpl obj) {
                return obj.gettxtLocationName();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.settxtLocationName((String) value);
            }
        }
        ,
        txtSupplierName {
            public Object get(PaymentMasterImpl obj) {
                return obj.gettxtSupplierName();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.settxtSupplierName((String) value);
            }
        }
        ,
        txtBranchName {
            public Object get(PaymentMasterImpl obj) {
                return obj.gettxtBranchName();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.settxtBranchName((String) value);
            }
        }
        ,
        txtErrorMessage {
            public Object get(PaymentMasterImpl obj) {
                return obj.gettxtErrorMessage();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.settxtErrorMessage((String) value);
            }
        }
        ,
        BankRefNo {
            public Object get(PaymentMasterImpl obj) {
                return obj.getBankRefNo();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setBankRefNo((String) value);
            }
        }
        ,
        StaxCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getStaxCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setStaxCode((Integer) value);
            }
        }
        ,
        TaxCode {
            public Object get(PaymentMasterImpl obj) {
                return obj.getTaxCode();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setTaxCode((Integer) value);
            }
        }
        ,
        txtNetAmount {
            public Object get(PaymentMasterImpl obj) {
                return obj.gettxtNetAmount();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.settxtNetAmount((BigDecimal) value);
            }
        }
        ,
        Payee {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPayee();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPayee((String) value);
            }
        }
        ,
        PaymentDetail {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPaymentDetail();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AllLocations {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAllLocations();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAllLocations((EntityImpl) value);
            }
        }
        ,
        PuSuppliers {
            public Object get(PaymentMasterImpl obj) {
                return obj.getPuSuppliers();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setPuSuppliers((PuSuppliersImpl) value);
            }
        }
        ,
        AllBankBranches {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAllBankBranches();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAllBankBranches((EntityImpl) value);
            }
        }
        ,
        AccVwFuncUserBackDateAllowed {
            public Object get(PaymentMasterImpl obj) {
                return obj.getAccVwFuncUserBackDateAllowed();
            }

            public void put(PaymentMasterImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PaymentMasterImpl object);

        public abstract void put(PaymentMasterImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PAYMENTCODE = AttributesEnum.PaymentCode.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int INVOICECODE = AttributesEnum.InvoiceCode.index();
    public static final int PAYMENTMODE = AttributesEnum.PaymentMode.index();
    public static final int PAYMENTTYPE = AttributesEnum.PaymentType.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int PAYMENTAMOUNT = AttributesEnum.PaymentAmount.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int REFVOUCHERNO = AttributesEnum.RefVoucherNo.index();
    public static final int SUBMIT = AttributesEnum.Submit.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POSTTOINTFACE = AttributesEnum.PostToIntFace.index();
    public static final int POSTTOGL = AttributesEnum.PostToGl.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int CHEQUENO = AttributesEnum.ChequeNo.index();
    public static final int CHEQUEDATE = AttributesEnum.ChequeDate.index();
    public static final int BANKID = AttributesEnum.Bankid.index();
    public static final int BRANCHID = AttributesEnum.Branchid.index();
    public static final int TAXPAID = AttributesEnum.TaxPaid.index();
    public static final int APPOSTED = AttributesEnum.ApPosted.index();
    public static final int BOOKID = AttributesEnum.Bookid.index();
    public static final int ADTAXCODE = AttributesEnum.AdtaxCode.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int LOCALFLAG = AttributesEnum.LocalFlag.index();
    public static final int IBDOCTYPEID = AttributesEnum.IbdocTypeId.index();
    public static final int BANKLOCID = AttributesEnum.BankLocid.index();
    public static final int NARRATION = AttributesEnum.Narration.index();
    public static final int PERMANETID = AttributesEnum.PermanetId.index();
    public static final int SUBMITDATE = AttributesEnum.SubmitDate.index();
    public static final int PAYEENAME = AttributesEnum.PayeeName.index();
    public static final int AUDITORCHECK = AttributesEnum.AuditorCheck.index();
    public static final int AUDITREMARKS = AttributesEnum.AuditRemarks.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int FCURRPAYAMOUNT = AttributesEnum.FcurrPayAmount.index();
    public static final int FCURRTAXAMOUNT = AttributesEnum.FcurrTaxAmount.index();
    public static final int NARRATIONRESCUE2 = AttributesEnum.NarrationRescue2.index();
    public static final int REFDOCTYPEID = AttributesEnum.RefDoctypeid.index();
    public static final int REFDOCUMENTID = AttributesEnum.RefDocumentId.index();
    public static final int OTFEX = AttributesEnum.OtfEx.index();
    public static final int APPROVEDMEMOID = AttributesEnum.ApprovedMemoId.index();
    public static final int AUDITORCHECKBY = AttributesEnum.AuditorCheckBy.index();
    public static final int AUDITORCHECKDATE = AttributesEnum.AuditorCheckDate.index();
    public static final int AUDITORCHECKREMARKS = AttributesEnum.AuditorCheckRemarks.index();
    public static final int FCURRSTAXAMOUNT = AttributesEnum.FcurrStaxAmount.index();
    public static final int STAXAMOUNT = AttributesEnum.StaxAmount.index();
    public static final int ADSALESTAXCODE = AttributesEnum.AdsalesTaxCode.index();
    public static final int PAYMENTSEQ = AttributesEnum.Paymentseq.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTBRANCHNAME = AttributesEnum.txtBranchName.index();
    public static final int TXTERRORMESSAGE = AttributesEnum.txtErrorMessage.index();
    public static final int BANKREFNO = AttributesEnum.BankRefNo.index();
    public static final int STAXCODE = AttributesEnum.StaxCode.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int PAYEE = AttributesEnum.Payee.index();
    public static final int PAYMENTDETAIL = AttributesEnum.PaymentDetail.index();
    public static final int ALLLOCATIONS = AttributesEnum.AllLocations.index();
    public static final int PUSUPPLIERS = AttributesEnum.PuSuppliers.index();
    public static final int ALLBANKBRANCHES = AttributesEnum.AllBankBranches.index();
    public static final int ACCVWFUNCUSERBACKDATEALLOWED = AttributesEnum.AccVwFuncUserBackDateAllowed.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PaymentMasterImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolaps.erpsolapsmodel.erpsolapseo.PaymentMaster");
    }


    /**
     * Gets the attribute value for PaymentCode, using the alias name PaymentCode.
     * @return the value of PaymentCode
     */
    public String getPaymentCode() {
        return (String) getAttributeInternal(PAYMENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentCode.
     * @param value value to set the PaymentCode
     */
    public void setPaymentCode(String value) {
        setAttributeInternal(PAYMENTCODE, value);
    }

    /**
     * Gets the attribute value for DocTypeId, using the alias name DocTypeId.
     * @return the value of DocTypeId
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocTypeId.
     * @param value value to set the DocTypeId
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for InvoiceCode, using the alias name InvoiceCode.
     * @return the value of InvoiceCode
     */
    public String getInvoiceCode() {
        return (String) getAttributeInternal(INVOICECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceCode.
     * @param value value to set the InvoiceCode
     */
    public void setInvoiceCode(String value) {
        setAttributeInternal(INVOICECODE, value);
    }

    /**
     * Gets the attribute value for PaymentMode, using the alias name PaymentMode.
     * @return the value of PaymentMode
     */
    public String getPaymentMode() {
        return (String) getAttributeInternal(PAYMENTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentMode.
     * @param value value to set the PaymentMode
     */
    public void setPaymentMode(String value) {
        setAttributeInternal(PAYMENTMODE, value);
    }

    /**
     * Gets the attribute value for PaymentType, using the alias name PaymentType.
     * @return the value of PaymentType
     */
    public String getPaymentType() {
        return (String) getAttributeInternal(PAYMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentType.
     * @param value value to set the PaymentType
     */
    public void setPaymentType(String value) {
        setAttributeInternal(PAYMENTTYPE, value);
    }

    /**
     * Gets the attribute value for Supplierid, using the alias name Supplierid.
     * @return the value of Supplierid
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierid.
     * @param value value to set the Supplierid
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for PaymentAmount, using the alias name PaymentAmount.
     * @return the value of PaymentAmount
     */
    public BigDecimal getPaymentAmount() {
        return (BigDecimal) getAttributeInternal(PAYMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentAmount.
     * @param value value to set the PaymentAmount
     */
    public void setPaymentAmount(BigDecimal value) {
        setAttributeInternal(PAYMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for PaymentDate, using the alias name PaymentDate.
     * @return the value of PaymentDate
     */
    public Date getPaymentDate() {
        return (Date) getAttributeInternal(PAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentDate.
     * @param value value to set the PaymentDate
     */
    public void setPaymentDate(Date value) {
        setAttributeInternal(PAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for RefVoucherNo, using the alias name RefVoucherNo.
     * @return the value of RefVoucherNo
     */
    public String getRefVoucherNo() {
        return (String) getAttributeInternal(REFVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefVoucherNo.
     * @param value value to set the RefVoucherNo
     */
    public void setRefVoucherNo(String value) {
        setAttributeInternal(REFVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for Submit, using the alias name Submit.
     * @return the value of Submit
     */
    public String getSubmit() {
        return (String) getAttributeInternal(SUBMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Submit.
     * @param value value to set the Submit
     */
    public void setSubmit(String value) {
        setAttributeInternal(SUBMIT, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for PostToIntFace, using the alias name PostToIntFace.
     * @return the value of PostToIntFace
     */
    public String getPostToIntFace() {
        return (String) getAttributeInternal(POSTTOINTFACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostToIntFace.
     * @param value value to set the PostToIntFace
     */
    public void setPostToIntFace(String value) {
        setAttributeInternal(POSTTOINTFACE, value);
    }

    /**
     * Gets the attribute value for PostToGl, using the alias name PostToGl.
     * @return the value of PostToGl
     */
    public String getPostToGl() {
        return (String) getAttributeInternal(POSTTOGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostToGl.
     * @param value value to set the PostToGl
     */
    public void setPostToGl(String value) {
        setAttributeInternal(POSTTOGL, value);
    }

    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Deptid, using the alias name Deptid.
     * @return the value of Deptid
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deptid.
     * @param value value to set the Deptid
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for ChequeNo, using the alias name ChequeNo.
     * @return the value of ChequeNo
     */
    public String getChequeNo() {
        return (String) getAttributeInternal(CHEQUENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChequeNo.
     * @param value value to set the ChequeNo
     */
    public void setChequeNo(String value) {
        setAttributeInternal(CHEQUENO, value);
    }

    /**
     * Gets the attribute value for ChequeDate, using the alias name ChequeDate.
     * @return the value of ChequeDate
     */
    public Date getChequeDate() {
        return (Date) getAttributeInternal(CHEQUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChequeDate.
     * @param value value to set the ChequeDate
     */
    public void setChequeDate(Date value) {
        setAttributeInternal(CHEQUEDATE, value);
    }

    /**
     * Gets the attribute value for Bankid, using the alias name Bankid.
     * @return the value of Bankid
     */
    public String getBankid() {
        return (String) getAttributeInternal(BANKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bankid.
     * @param value value to set the Bankid
     */
    public void setBankid(String value) {
        setAttributeInternal(BANKID, value);
    }

    /**
     * Gets the attribute value for Branchid, using the alias name Branchid.
     * @return the value of Branchid
     */
    public String getBranchid() {
        return (String) getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Branchid.
     * @param value value to set the Branchid
     */
    public void setBranchid(String value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**
     * Gets the attribute value for TaxPaid, using the alias name TaxPaid.
     * @return the value of TaxPaid
     */
    public String getTaxPaid() {
        return (String) getAttributeInternal(TAXPAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxPaid.
     * @param value value to set the TaxPaid
     */
    public void setTaxPaid(String value) {
        setAttributeInternal(TAXPAID, value);
    }

    /**
     * Gets the attribute value for ApPosted, using the alias name ApPosted.
     * @return the value of ApPosted
     */
    public String getApPosted() {
        return (String) getAttributeInternal(APPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApPosted.
     * @param value value to set the ApPosted
     */
    public void setApPosted(String value) {
        setAttributeInternal(APPOSTED, value);
    }

    /**
     * Gets the attribute value for Bookid, using the alias name Bookid.
     * @return the value of Bookid
     */
    public String getBookid() {
        return (String) getAttributeInternal(BOOKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bookid.
     * @param value value to set the Bookid
     */
    public void setBookid(String value) {
        setAttributeInternal(BOOKID, value);
    }

    /**
     * Gets the attribute value for AdtaxCode, using the alias name AdtaxCode.
     * @return the value of AdtaxCode
     */
    public BigDecimal getAdtaxCode() {
        return (BigDecimal) getAttributeInternal(ADTAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdtaxCode.
     * @param value value to set the AdtaxCode
     */
    public void setAdtaxCode(BigDecimal value) {
        setAttributeInternal(ADTAXCODE, value);
    }

    /**
     * Gets the attribute value for TaxAmount, using the alias name TaxAmount.
     * @return the value of TaxAmount
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxAmount.
     * @param value value to set the TaxAmount
     */
    public void setTaxAmount(BigDecimal value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for LocalFlag, using the alias name LocalFlag.
     * @return the value of LocalFlag
     */
    public String getLocalFlag() {
        return (String) getAttributeInternal(LOCALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocalFlag.
     * @param value value to set the LocalFlag
     */
    public void setLocalFlag(String value) {
        setAttributeInternal(LOCALFLAG, value);
    }

    /**
     * Gets the attribute value for IbdocTypeId, using the alias name IbdocTypeId.
     * @return the value of IbdocTypeId
     */
    public String getIbdocTypeId() {
        return (String) getAttributeInternal(IBDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IbdocTypeId.
     * @param value value to set the IbdocTypeId
     */
    public void setIbdocTypeId(String value) {
        setAttributeInternal(IBDOCTYPEID, value);
    }

    /**
     * Gets the attribute value for BankLocid, using the alias name BankLocid.
     * @return the value of BankLocid
     */
    public String getBankLocid() {
        return (String) getAttributeInternal(BANKLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankLocid.
     * @param value value to set the BankLocid
     */
    public void setBankLocid(String value) {
        setAttributeInternal(BANKLOCID, value);
    }

    /**
     * Gets the attribute value for Narration, using the alias name Narration.
     * @return the value of Narration
     */
    public String getNarration() {
        return (String) getAttributeInternal(NARRATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Narration.
     * @param value value to set the Narration
     */
    public void setNarration(String value) {
        setAttributeInternal(NARRATION, value);
    }

    /**
     * Gets the attribute value for PermanetId, using the alias name PermanetId.
     * @return the value of PermanetId
     */
    public String getPermanetId() {
        return (String) getAttributeInternal(PERMANETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PermanetId.
     * @param value value to set the PermanetId
     */
    public void setPermanetId(String value) {
        setAttributeInternal(PERMANETID, value);
    }

    /**
     * Gets the attribute value for SubmitDate, using the alias name SubmitDate.
     * @return the value of SubmitDate
     */
    public Date getSubmitDate() {
        return (Date) getAttributeInternal(SUBMITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitDate.
     * @param value value to set the SubmitDate
     */
    public void setSubmitDate(Date value) {
        setAttributeInternal(SUBMITDATE, value);
    }

    /**
     * Gets the attribute value for PayeeName, using the alias name PayeeName.
     * @return the value of PayeeName
     */
    public String getPayeeName() {
        return (String) getAttributeInternal(PAYEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayeeName.
     * @param value value to set the PayeeName
     */
    public void setPayeeName(String value) {
        setAttributeInternal(PAYEENAME, value);
    }

    /**
     * Gets the attribute value for AuditorCheck, using the alias name AuditorCheck.
     * @return the value of AuditorCheck
     */
    public String getAuditorCheck() {
        return (String) getAttributeInternal(AUDITORCHECK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheck.
     * @param value value to set the AuditorCheck
     */
    public void setAuditorCheck(String value) {
        setAttributeInternal(AUDITORCHECK, value);
    }

    /**
     * Gets the attribute value for AuditRemarks, using the alias name AuditRemarks.
     * @return the value of AuditRemarks
     */
    public String getAuditRemarks() {
        return (String) getAttributeInternal(AUDITREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditRemarks.
     * @param value value to set the AuditRemarks
     */
    public void setAuditRemarks(String value) {
        setAttributeInternal(AUDITREMARKS, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for Postedby, using the alias name Postedby.
     * @return the value of Postedby
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postedby.
     * @param value value to set the Postedby
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the value of ExchangeRate
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for LocCurrcode, using the alias name LocCurrcode.
     * @return the value of LocCurrcode
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocCurrcode.
     * @param value value to set the LocCurrcode
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for FcurrPayAmount, using the alias name FcurrPayAmount.
     * @return the value of FcurrPayAmount
     */
    public BigDecimal getFcurrPayAmount() {
        return (BigDecimal) getAttributeInternal(FCURRPAYAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrPayAmount.
     * @param value value to set the FcurrPayAmount
     */
    public void setFcurrPayAmount(BigDecimal value) {
        setAttributeInternal(FCURRPAYAMOUNT, value);
    }

    /**
     * Gets the attribute value for FcurrTaxAmount, using the alias name FcurrTaxAmount.
     * @return the value of FcurrTaxAmount
     */
    public BigDecimal getFcurrTaxAmount() {
        return (BigDecimal) getAttributeInternal(FCURRTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrTaxAmount.
     * @param value value to set the FcurrTaxAmount
     */
    public void setFcurrTaxAmount(BigDecimal value) {
        setAttributeInternal(FCURRTAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for NarrationRescue2, using the alias name NarrationRescue2.
     * @return the value of NarrationRescue2
     */
    public String getNarrationRescue2() {
        return (String) getAttributeInternal(NARRATIONRESCUE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for NarrationRescue2.
     * @param value value to set the NarrationRescue2
     */
    public void setNarrationRescue2(String value) {
        setAttributeInternal(NARRATIONRESCUE2, value);
    }

    /**
     * Gets the attribute value for RefDoctypeid, using the alias name RefDoctypeid.
     * @return the value of RefDoctypeid
     */
    public String getRefDoctypeid() {
        return (String) getAttributeInternal(REFDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefDoctypeid.
     * @param value value to set the RefDoctypeid
     */
    public void setRefDoctypeid(String value) {
        setAttributeInternal(REFDOCTYPEID, value);
    }

    /**
     * Gets the attribute value for RefDocumentId, using the alias name RefDocumentId.
     * @return the value of RefDocumentId
     */
    public String getRefDocumentId() {
        return (String) getAttributeInternal(REFDOCUMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefDocumentId.
     * @param value value to set the RefDocumentId
     */
    public void setRefDocumentId(String value) {
        setAttributeInternal(REFDOCUMENTID, value);
    }

    /**
     * Gets the attribute value for OtfEx, using the alias name OtfEx.
     * @return the value of OtfEx
     */
    public String getOtfEx() {
        return (String) getAttributeInternal(OTFEX);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtfEx.
     * @param value value to set the OtfEx
     */
    public void setOtfEx(String value) {
        setAttributeInternal(OTFEX, value);
    }

    /**
     * Gets the attribute value for ApprovedMemoId, using the alias name ApprovedMemoId.
     * @return the value of ApprovedMemoId
     */
    public String getApprovedMemoId() {
        return (String) getAttributeInternal(APPROVEDMEMOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovedMemoId.
     * @param value value to set the ApprovedMemoId
     */
    public void setApprovedMemoId(String value) {
        setAttributeInternal(APPROVEDMEMOID, value);
    }

    /**
     * Gets the attribute value for AuditorCheckBy, using the alias name AuditorCheckBy.
     * @return the value of AuditorCheckBy
     */
    public String getAuditorCheckBy() {
        return (String) getAttributeInternal(AUDITORCHECKBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckBy.
     * @param value value to set the AuditorCheckBy
     */
    public void setAuditorCheckBy(String value) {
        setAttributeInternal(AUDITORCHECKBY, value);
    }

    /**
     * Gets the attribute value for AuditorCheckDate, using the alias name AuditorCheckDate.
     * @return the value of AuditorCheckDate
     */
    public Date getAuditorCheckDate() {
        return (Date) getAttributeInternal(AUDITORCHECKDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckDate.
     * @param value value to set the AuditorCheckDate
     */
    public void setAuditorCheckDate(Date value) {
        setAttributeInternal(AUDITORCHECKDATE, value);
    }

    /**
     * Gets the attribute value for AuditorCheckRemarks, using the alias name AuditorCheckRemarks.
     * @return the value of AuditorCheckRemarks
     */
    public String getAuditorCheckRemarks() {
        return (String) getAttributeInternal(AUDITORCHECKREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheckRemarks.
     * @param value value to set the AuditorCheckRemarks
     */
    public void setAuditorCheckRemarks(String value) {
        setAttributeInternal(AUDITORCHECKREMARKS, value);
    }

    /**
     * Gets the attribute value for FcurrStaxAmount, using the alias name FcurrStaxAmount.
     * @return the value of FcurrStaxAmount
     */
    public BigDecimal getFcurrStaxAmount() {
        return (BigDecimal) getAttributeInternal(FCURRSTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrStaxAmount.
     * @param value value to set the FcurrStaxAmount
     */
    public void setFcurrStaxAmount(BigDecimal value) {
        setAttributeInternal(FCURRSTAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for StaxAmount, using the alias name StaxAmount.
     * @return the value of StaxAmount
     */
    public BigDecimal getStaxAmount() {
        return (BigDecimal) getAttributeInternal(STAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaxAmount.
     * @param value value to set the StaxAmount
     */
    public void setStaxAmount(BigDecimal value) {
        setAttributeInternal(STAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for AdsalesTaxCode, using the alias name AdsalesTaxCode.
     * @return the value of AdsalesTaxCode
     */
    public BigDecimal getAdsalesTaxCode() {
        return (BigDecimal) getAttributeInternal(ADSALESTAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdsalesTaxCode.
     * @param value value to set the AdsalesTaxCode
     */
    public void setAdsalesTaxCode(BigDecimal value) {
        setAttributeInternal(ADSALESTAXCODE, value);
    }

    /**
     * Gets the attribute value for Paymentseq, using the alias name Paymentseq.
     * @return the value of Paymentseq
     */
    public Integer getPaymentseq() {
        return (Integer) getAttributeInternal(PAYMENTSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Paymentseq.
     * @param value value to set the Paymentseq
     */
    public void setPaymentseq(Integer value) {
        setAttributeInternal(PAYMENTSEQ, value);
    }

    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for txtSupplierName, using the alias name txtSupplierName.
     * @return the value of txtSupplierName
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSupplierName.
     * @param value value to set the txtSupplierName
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for txtBranchName, using the alias name txtBranchName.
     * @return the value of txtBranchName
     */
    public String gettxtBranchName() {
        return (String) getAttributeInternal(TXTBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtBranchName.
     * @param value value to set the txtBranchName
     */
    public void settxtBranchName(String value) {
        setAttributeInternal(TXTBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for txtErrorMessage, using the alias name txtErrorMessage.
     * @return the value of txtErrorMessage
     */
    public String gettxtErrorMessage() {
        return (String) getAttributeInternal(TXTERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtErrorMessage.
     * @param value value to set the txtErrorMessage
     */
    public void settxtErrorMessage(String value) {
        setAttributeInternal(TXTERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for BankRefNo, using the alias name BankRefNo.
     * @return the value of BankRefNo
     */
    public String getBankRefNo() {
        return (String) getAttributeInternal(BANKREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankRefNo.
     * @param value value to set the BankRefNo
     */
    public void setBankRefNo(String value) {
        setAttributeInternal(BANKREFNO, value==null?null:value.toUpperCase());
    }

    /**
     * Gets the attribute value for StaxCode, using the alias name StaxCode.
     * @return the value of StaxCode
     */
    public Integer getStaxCode() {
        return (Integer) getAttributeInternal(STAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaxCode.
     * @param value value to set the StaxCode
     */
    public void setStaxCode(Integer value) {
        setAttributeInternal(STAXCODE, value);
    }

    /**
     * Gets the attribute value for TaxCode, using the alias name TaxCode.
     * @return the value of TaxCode
     */
    public Integer getTaxCode() {
        return (Integer) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxCode.
     * @param value value to set the TaxCode
     */
    public void setTaxCode(Integer value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for txtNetAmount, using the alias name txtNetAmount.
     * @return the value of txtNetAmount
     */
    public BigDecimal gettxtNetAmount() {
        return (BigDecimal) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtNetAmount.
     * @param value value to set the txtNetAmount
     */
    public void settxtNetAmount(BigDecimal value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for Payee, using the alias name Payee.
     * @return the value of Payee
     */
    public String getPayee() {
        return (String) getAttributeInternal(PAYEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Payee.
     * @param value value to set the Payee
     */
    public void setPayee(String value) {
        setAttributeInternal(PAYEE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPaymentDetail() {
        return (RowIterator) getAttributeInternal(PAYMENTDETAIL);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllLocations() {
        return (EntityImpl) getAttributeInternal(ALLLOCATIONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllLocations(EntityImpl value) {
        setAttributeInternal(ALLLOCATIONS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public PuSuppliersImpl getPuSuppliers() {
        return (PuSuppliersImpl) getAttributeInternal(PUSUPPLIERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPuSuppliers(PuSuppliersImpl value) {
        setAttributeInternal(PUSUPPLIERS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllBankBranches() {
        return (EntityImpl) getAttributeInternal(ALLBANKBRANCHES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllBankBranches(EntityImpl value) {
        setAttributeInternal(ALLBANKBRANCHES, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncUserBackDateAllowed.
     */
    public RowSet getAccVwFuncUserBackDateAllowed() {
        return (RowSet) getAttributeInternal(ACCVWFUNCUSERBACKDATEALLOWED);
    }


    /**
     * @param paymentseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer paymentseq) {
        return new Key(new Object[] { paymentseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Paymentseq");
        setERPSolPKSeqName("PAYMENT_MASTER_SEQ");
        setCompanyid(ERPSolGlobClassModel.doGetUserCompanyCode());
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
        
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            ;
           String pkValue =
                " fun_payment_id('" + ERPSolGlobClassModel.doGetUserCompanyCode() + "','" +
                ERPSolGlobClassModel.doGetUserLocationCode() + "','B',TO_DATE('" + getPaymentDate() + "','YYYY-MM-DD'))";
            System.out.println(pkValue + "pk value");
            String result =
                ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(PAYMENTCODE, result);            

        }
        if (operation != DML_DELETE) {
            populateAttributeAsChanged(DOCTYPEID, getPaymentMode().toString().equals("CHQ") ? "PYMT" : "CPMT");
            populateAttributeAsChanged(PAYMENTAMOUNT, getFcurrPayAmount());
            populateAttributeAsChanged(TAXAMOUNT, getFcurrTaxAmount());
            populateAttributeAsChanged(STAXAMOUNT, getFcurrStaxAmount());
        }
        super.doDML(operation, e);
    }
    
    @Override
    public void afterCommit(TransactionEvent transactionEvent) {
        // TODO Implement this method
        System.out.println("committing");
        if (getSubmit().equals("Y")) {
           super.afterCommit(transactionEvent);
           return;
        }        
            CallableStatement cs=this.getDBTransaction().createCallableStatement("begin  PKG_GENERATE_ACCOUNTING.GV_POST_TO_INTERFACE:='N'; PKG_GENERATE_ACCOUNTING.PROC_GENERATE_PAYMENT_ACCOUNT('"+getPaymentCode()+"'); commit; PKG_GENERATE_ACCOUNTING.GV_POST_TO_INTERFACE:='Y'; END;", 1);
            try {
                cs.executeUpdate();
            } catch (SQLException e) {
        //            this.getCurrentRow().setAttribute("Submit", "N");
            JboException ex=new JboException(e.getMessage());
            ex.setSeverity(JboException.SEVERITY_WARNING);
            throw ex;
                
//                System.out.println(e.getMessage()+ "this is message");
//                throw new JboException("Unable to supervise ");
            }
            finally{
                try {
                    cs.close();
                } catch (SQLException e) {
                }
            }
        
        super.afterCommit(transactionEvent);
    }
}

