package erpsolaps.erpsolapsmodel.erpsolapseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 01 09:29:24 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuSuppliersImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Supplierid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSupplierid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSupplierid((String) value);
            }
        }
        ,
        Companyid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCompanyid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCompanyid((String) value);
            }
        }
        ,
        Paymenttermid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getPaymenttermid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setPaymenttermid((String) value);
            }
        }
        ,
        Deliverytermid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getDeliverytermid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setDeliverytermid((String) value);
            }
        }
        ,
        Suppsegmentid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSuppsegmentid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSuppsegmentid((String) value);
            }
        }
        ,
        Suppcategoryid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSuppcategoryid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSuppcategoryid((String) value);
            }
        }
        ,
        SuppName {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSuppName();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSuppName((String) value);
            }
        }
        ,
        SuppShortName {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSuppShortName();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSuppShortName((String) value);
            }
        }
        ,
        ContactName {
            public Object get(PuSuppliersImpl obj) {
                return obj.getContactName();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setContactName((String) value);
            }
        }
        ,
        ContactAddress {
            public Object get(PuSuppliersImpl obj) {
                return obj.getContactAddress();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setContactAddress((String) value);
            }
        }
        ,
        Currid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCurrid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCurrid((String) value);
            }
        }
        ,
        InternationalSupplier {
            public Object get(PuSuppliersImpl obj) {
                return obj.getInternationalSupplier();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setInternationalSupplier((String) value);
            }
        }
        ,
        Createdby {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCreatedby();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        Modifiedby {
            public Object get(PuSuppliersImpl obj) {
                return obj.getModifiedby();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(PuSuppliersImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        TelNo {
            public Object get(PuSuppliersImpl obj) {
                return obj.getTelNo();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setTelNo((String) value);
            }
        }
        ,
        MobileNo {
            public Object get(PuSuppliersImpl obj) {
                return obj.getMobileNo();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setMobileNo((String) value);
            }
        }
        ,
        Email {
            public Object get(PuSuppliersImpl obj) {
                return obj.getEmail();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setEmail((String) value);
            }
        }
        ,
        FaxNo {
            public Object get(PuSuppliersImpl obj) {
                return obj.getFaxNo();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setFaxNo((String) value);
            }
        }
        ,
        Country {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCountry();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCountry((String) value);
            }
        }
        ,
        City {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCity();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCity((String) value);
            }
        }
        ,
        TaxCode {
            public Object get(PuSuppliersImpl obj) {
                return obj.getTaxCode();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setTaxCode((Integer) value);
            }
        }
        ,
        Taxexempt {
            public Object get(PuSuppliersImpl obj) {
                return obj.getTaxexempt();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setTaxexempt((String) value);
            }
        }
        ,
        Glcode {
            public Object get(PuSuppliersImpl obj) {
                return obj.getGlcode();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setGlcode((String) value);
            }
        }
        ,
        Costcenter {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCostcenter();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCostcenter((String) value);
            }
        }
        ,
        Priority {
            public Object get(PuSuppliersImpl obj) {
                return obj.getPriority();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setPriority((String) value);
            }
        }
        ,
        Climit {
            public Object get(PuSuppliersImpl obj) {
                return obj.getClimit();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setClimit((BigDecimal) value);
            }
        }
        ,
        Ntnno {
            public Object get(PuSuppliersImpl obj) {
                return obj.getNtnno();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setNtnno((String) value);
            }
        }
        ,
        Advglcode {
            public Object get(PuSuppliersImpl obj) {
                return obj.getAdvglcode();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setAdvglcode((String) value);
            }
        }
        ,
        Advcostcenter {
            public Object get(PuSuppliersImpl obj) {
                return obj.getAdvcostcenter();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setAdvcostcenter((String) value);
            }
        }
        ,
        Locationid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getLocationid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setLocationid((String) value);
            }
        }
        ,
        SuppType {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSuppType();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSuppType((String) value);
            }
        }
        ,
        StaxNo {
            public Object get(PuSuppliersImpl obj) {
                return obj.getStaxNo();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setStaxNo((String) value);
            }
        }
        ,
        StaxNoTemp {
            public Object get(PuSuppliersImpl obj) {
                return obj.getStaxNoTemp();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setStaxNoTemp((String) value);
            }
        }
        ,
        CreditLimit {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCreditLimit();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCreditLimit((BigDecimal) value);
            }
        }
        ,
        Cglcode {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCglcode();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCglcode((String) value);
            }
        }
        ,
        Ccostcenter {
            public Object get(PuSuppliersImpl obj) {
                return obj.getCcostcenter();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setCcostcenter((String) value);
            }
        }
        ,
        DebitNoteWithoutReference {
            public Object get(PuSuppliersImpl obj) {
                return obj.getDebitNoteWithoutReference();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setDebitNoteWithoutReference((String) value);
            }
        }
        ,
        IsReceiptPayment {
            public Object get(PuSuppliersImpl obj) {
                return obj.getIsReceiptPayment();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setIsReceiptPayment((String) value);
            }
        }
        ,
        IsMigrated {
            public Object get(PuSuppliersImpl obj) {
                return obj.getIsMigrated();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setIsMigrated((String) value);
            }
        }
        ,
        MigratedDate {
            public Object get(PuSuppliersImpl obj) {
                return obj.getMigratedDate();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setMigratedDate((Date) value);
            }
        }
        ,
        Child {
            public Object get(PuSuppliersImpl obj) {
                return obj.getChild();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setChild((String) value);
            }
        }
        ,
        Psuppid {
            public Object get(PuSuppliersImpl obj) {
                return obj.getPsuppid();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setPsuppid((String) value);
            }
        }
        ,
        Supplierseq {
            public Object get(PuSuppliersImpl obj) {
                return obj.getSupplierseq();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setSupplierseq((Integer) value);
            }
        }
        ,
        OtherBills {
            public Object get(PuSuppliersImpl obj) {
                return obj.getOtherBills();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentMaster {
            public Object get(PuSuppliersImpl obj) {
                return obj.getPaymentMaster();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NoteMaster {
            public Object get(PuSuppliersImpl obj) {
                return obj.getNoteMaster();
            }

            public void put(PuSuppliersImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PuSuppliersImpl object);

        public abstract void put(PuSuppliersImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int PAYMENTTERMID = AttributesEnum.Paymenttermid.index();
    public static final int DELIVERYTERMID = AttributesEnum.Deliverytermid.index();
    public static final int SUPPSEGMENTID = AttributesEnum.Suppsegmentid.index();
    public static final int SUPPCATEGORYID = AttributesEnum.Suppcategoryid.index();
    public static final int SUPPNAME = AttributesEnum.SuppName.index();
    public static final int SUPPSHORTNAME = AttributesEnum.SuppShortName.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int CONTACTADDRESS = AttributesEnum.ContactAddress.index();
    public static final int CURRID = AttributesEnum.Currid.index();
    public static final int INTERNATIONALSUPPLIER = AttributesEnum.InternationalSupplier.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int TELNO = AttributesEnum.TelNo.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int FAXNO = AttributesEnum.FaxNo.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXEXEMPT = AttributesEnum.Taxexempt.index();
    public static final int GLCODE = AttributesEnum.Glcode.index();
    public static final int COSTCENTER = AttributesEnum.Costcenter.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int CLIMIT = AttributesEnum.Climit.index();
    public static final int NTNNO = AttributesEnum.Ntnno.index();
    public static final int ADVGLCODE = AttributesEnum.Advglcode.index();
    public static final int ADVCOSTCENTER = AttributesEnum.Advcostcenter.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SUPPTYPE = AttributesEnum.SuppType.index();
    public static final int STAXNO = AttributesEnum.StaxNo.index();
    public static final int STAXNOTEMP = AttributesEnum.StaxNoTemp.index();
    public static final int CREDITLIMIT = AttributesEnum.CreditLimit.index();
    public static final int CGLCODE = AttributesEnum.Cglcode.index();
    public static final int CCOSTCENTER = AttributesEnum.Ccostcenter.index();
    public static final int DEBITNOTEWITHOUTREFERENCE = AttributesEnum.DebitNoteWithoutReference.index();
    public static final int ISRECEIPTPAYMENT = AttributesEnum.IsReceiptPayment.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int CHILD = AttributesEnum.Child.index();
    public static final int PSUPPID = AttributesEnum.Psuppid.index();
    public static final int SUPPLIERSEQ = AttributesEnum.Supplierseq.index();
    public static final int OTHERBILLS = AttributesEnum.OtherBills.index();
    public static final int PAYMENTMASTER = AttributesEnum.PaymentMaster.index();
    public static final int NOTEMASTER = AttributesEnum.NoteMaster.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuSuppliersImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolaps.erpsolapsmodel.erpsolapseo.PuSuppliers");
    }


    /**
     * Gets the attribute value for Supplierid, using the alias name Supplierid.
     * @return the value of Supplierid
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierid.
     * @param value value to set the Supplierid
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for Paymenttermid, using the alias name Paymenttermid.
     * @return the value of Paymenttermid
     */
    public String getPaymenttermid() {
        return (String) getAttributeInternal(PAYMENTTERMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Paymenttermid.
     * @param value value to set the Paymenttermid
     */
    public void setPaymenttermid(String value) {
        setAttributeInternal(PAYMENTTERMID, value);
    }

    /**
     * Gets the attribute value for Deliverytermid, using the alias name Deliverytermid.
     * @return the value of Deliverytermid
     */
    public String getDeliverytermid() {
        return (String) getAttributeInternal(DELIVERYTERMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deliverytermid.
     * @param value value to set the Deliverytermid
     */
    public void setDeliverytermid(String value) {
        setAttributeInternal(DELIVERYTERMID, value);
    }

    /**
     * Gets the attribute value for Suppsegmentid, using the alias name Suppsegmentid.
     * @return the value of Suppsegmentid
     */
    public String getSuppsegmentid() {
        return (String) getAttributeInternal(SUPPSEGMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Suppsegmentid.
     * @param value value to set the Suppsegmentid
     */
    public void setSuppsegmentid(String value) {
        setAttributeInternal(SUPPSEGMENTID, value);
    }

    /**
     * Gets the attribute value for Suppcategoryid, using the alias name Suppcategoryid.
     * @return the value of Suppcategoryid
     */
    public String getSuppcategoryid() {
        return (String) getAttributeInternal(SUPPCATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Suppcategoryid.
     * @param value value to set the Suppcategoryid
     */
    public void setSuppcategoryid(String value) {
        setAttributeInternal(SUPPCATEGORYID, value);
    }

    /**
     * Gets the attribute value for SuppName, using the alias name SuppName.
     * @return the value of SuppName
     */
    public String getSuppName() {
        return (String) getAttributeInternal(SUPPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppName.
     * @param value value to set the SuppName
     */
    public void setSuppName(String value) {
        setAttributeInternal(SUPPNAME, value);
    }

    /**
     * Gets the attribute value for SuppShortName, using the alias name SuppShortName.
     * @return the value of SuppShortName
     */
    public String getSuppShortName() {
        return (String) getAttributeInternal(SUPPSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppShortName.
     * @param value value to set the SuppShortName
     */
    public void setSuppShortName(String value) {
        setAttributeInternal(SUPPSHORTNAME, value);
    }

    /**
     * Gets the attribute value for ContactName, using the alias name ContactName.
     * @return the value of ContactName
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactName.
     * @param value value to set the ContactName
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for ContactAddress, using the alias name ContactAddress.
     * @return the value of ContactAddress
     */
    public String getContactAddress() {
        return (String) getAttributeInternal(CONTACTADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactAddress.
     * @param value value to set the ContactAddress
     */
    public void setContactAddress(String value) {
        setAttributeInternal(CONTACTADDRESS, value);
    }

    /**
     * Gets the attribute value for Currid, using the alias name Currid.
     * @return the value of Currid
     */
    public String getCurrid() {
        return (String) getAttributeInternal(CURRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currid.
     * @param value value to set the Currid
     */
    public void setCurrid(String value) {
        setAttributeInternal(CURRID, value);
    }

    /**
     * Gets the attribute value for InternationalSupplier, using the alias name InternationalSupplier.
     * @return the value of InternationalSupplier
     */
    public String getInternationalSupplier() {
        return (String) getAttributeInternal(INTERNATIONALSUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for InternationalSupplier.
     * @param value value to set the InternationalSupplier
     */
    public void setInternationalSupplier(String value) {
        setAttributeInternal(INTERNATIONALSUPPLIER, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for TelNo, using the alias name TelNo.
     * @return the value of TelNo
     */
    public String getTelNo() {
        return (String) getAttributeInternal(TELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TelNo.
     * @param value value to set the TelNo
     */
    public void setTelNo(String value) {
        setAttributeInternal(TELNO, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for FaxNo, using the alias name FaxNo.
     * @return the value of FaxNo
     */
    public String getFaxNo() {
        return (String) getAttributeInternal(FAXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FaxNo.
     * @param value value to set the FaxNo
     */
    public void setFaxNo(String value) {
        setAttributeInternal(FAXNO, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the value of Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the value of City
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for TaxCode, using the alias name TaxCode.
     * @return the value of TaxCode
     */
    public Integer getTaxCode() {
        return (Integer) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxCode.
     * @param value value to set the TaxCode
     */
    public void setTaxCode(Integer value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for Taxexempt, using the alias name Taxexempt.
     * @return the value of Taxexempt
     */
    public String getTaxexempt() {
        return (String) getAttributeInternal(TAXEXEMPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Taxexempt.
     * @param value value to set the Taxexempt
     */
    public void setTaxexempt(String value) {
        setAttributeInternal(TAXEXEMPT, value);
    }

    /**
     * Gets the attribute value for Glcode, using the alias name Glcode.
     * @return the value of Glcode
     */
    public String getGlcode() {
        return (String) getAttributeInternal(GLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Glcode.
     * @param value value to set the Glcode
     */
    public void setGlcode(String value) {
        setAttributeInternal(GLCODE, value);
    }

    /**
     * Gets the attribute value for Costcenter, using the alias name Costcenter.
     * @return the value of Costcenter
     */
    public String getCostcenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Costcenter.
     * @param value value to set the Costcenter
     */
    public void setCostcenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for Priority, using the alias name Priority.
     * @return the value of Priority
     */
    public String getPriority() {
        return (String) getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Priority.
     * @param value value to set the Priority
     */
    public void setPriority(String value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for Climit, using the alias name Climit.
     * @return the value of Climit
     */
    public BigDecimal getClimit() {
        return (BigDecimal) getAttributeInternal(CLIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Climit.
     * @param value value to set the Climit
     */
    public void setClimit(BigDecimal value) {
        setAttributeInternal(CLIMIT, value);
    }

    /**
     * Gets the attribute value for Ntnno, using the alias name Ntnno.
     * @return the value of Ntnno
     */
    public String getNtnno() {
        return (String) getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ntnno.
     * @param value value to set the Ntnno
     */
    public void setNtnno(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for Advglcode, using the alias name Advglcode.
     * @return the value of Advglcode
     */
    public String getAdvglcode() {
        return (String) getAttributeInternal(ADVGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Advglcode.
     * @param value value to set the Advglcode
     */
    public void setAdvglcode(String value) {
        setAttributeInternal(ADVGLCODE, value);
    }

    /**
     * Gets the attribute value for Advcostcenter, using the alias name Advcostcenter.
     * @return the value of Advcostcenter
     */
    public String getAdvcostcenter() {
        return (String) getAttributeInternal(ADVCOSTCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Advcostcenter.
     * @param value value to set the Advcostcenter
     */
    public void setAdvcostcenter(String value) {
        setAttributeInternal(ADVCOSTCENTER, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for SuppType, using the alias name SuppType.
     * @return the value of SuppType
     */
    public String getSuppType() {
        return (String) getAttributeInternal(SUPPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppType.
     * @param value value to set the SuppType
     */
    public void setSuppType(String value) {
        setAttributeInternal(SUPPTYPE, value);
    }

    /**
     * Gets the attribute value for StaxNo, using the alias name StaxNo.
     * @return the value of StaxNo
     */
    public String getStaxNo() {
        return (String) getAttributeInternal(STAXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaxNo.
     * @param value value to set the StaxNo
     */
    public void setStaxNo(String value) {
        setAttributeInternal(STAXNO, value);
    }

    /**
     * Gets the attribute value for StaxNoTemp, using the alias name StaxNoTemp.
     * @return the value of StaxNoTemp
     */
    public String getStaxNoTemp() {
        return (String) getAttributeInternal(STAXNOTEMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaxNoTemp.
     * @param value value to set the StaxNoTemp
     */
    public void setStaxNoTemp(String value) {
        setAttributeInternal(STAXNOTEMP, value);
    }

    /**
     * Gets the attribute value for CreditLimit, using the alias name CreditLimit.
     * @return the value of CreditLimit
     */
    public BigDecimal getCreditLimit() {
        return (BigDecimal) getAttributeInternal(CREDITLIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreditLimit.
     * @param value value to set the CreditLimit
     */
    public void setCreditLimit(BigDecimal value) {
        setAttributeInternal(CREDITLIMIT, value);
    }

    /**
     * Gets the attribute value for Cglcode, using the alias name Cglcode.
     * @return the value of Cglcode
     */
    public String getCglcode() {
        return (String) getAttributeInternal(CGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cglcode.
     * @param value value to set the Cglcode
     */
    public void setCglcode(String value) {
        setAttributeInternal(CGLCODE, value);
    }

    /**
     * Gets the attribute value for Ccostcenter, using the alias name Ccostcenter.
     * @return the value of Ccostcenter
     */
    public String getCcostcenter() {
        return (String) getAttributeInternal(CCOSTCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ccostcenter.
     * @param value value to set the Ccostcenter
     */
    public void setCcostcenter(String value) {
        setAttributeInternal(CCOSTCENTER, value);
    }

    /**
     * Gets the attribute value for DebitNoteWithoutReference, using the alias name DebitNoteWithoutReference.
     * @return the value of DebitNoteWithoutReference
     */
    public String getDebitNoteWithoutReference() {
        return (String) getAttributeInternal(DEBITNOTEWITHOUTREFERENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DebitNoteWithoutReference.
     * @param value value to set the DebitNoteWithoutReference
     */
    public void setDebitNoteWithoutReference(String value) {
        setAttributeInternal(DEBITNOTEWITHOUTREFERENCE, value);
    }

    /**
     * Gets the attribute value for IsReceiptPayment, using the alias name IsReceiptPayment.
     * @return the value of IsReceiptPayment
     */
    public String getIsReceiptPayment() {
        return (String) getAttributeInternal(ISRECEIPTPAYMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsReceiptPayment.
     * @param value value to set the IsReceiptPayment
     */
    public void setIsReceiptPayment(String value) {
        setAttributeInternal(ISRECEIPTPAYMENT, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for Child, using the alias name Child.
     * @return the value of Child
     */
    public String getChild() {
        return (String) getAttributeInternal(CHILD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Child.
     * @param value value to set the Child
     */
    public void setChild(String value) {
        setAttributeInternal(CHILD, value);
    }

    /**
     * Gets the attribute value for Psuppid, using the alias name Psuppid.
     * @return the value of Psuppid
     */
    public String getPsuppid() {
        return (String) getAttributeInternal(PSUPPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Psuppid.
     * @param value value to set the Psuppid
     */
    public void setPsuppid(String value) {
        setAttributeInternal(PSUPPID, value);
    }

    /**
     * Gets the attribute value for Supplierseq, using the alias name Supplierseq.
     * @return the value of Supplierseq
     */
    public Integer getSupplierseq() {
        return (Integer) getAttributeInternal(SUPPLIERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierseq.
     * @param value value to set the Supplierseq
     */
    public void setSupplierseq(Integer value) {
        setAttributeInternal(SUPPLIERSEQ, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getOtherBills() {
        return (RowIterator) getAttributeInternal(OTHERBILLS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPaymentMaster() {
        return (RowIterator) getAttributeInternal(PAYMENTMASTER);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getNoteMaster() {
        return (RowIterator) getAttributeInternal(NOTEMASTER);
    }


    /**
     * @param supplierseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer supplierseq) {
        return new Key(new Object[] { supplierseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Supplierseq");
        setERPSolPKSeqName("PU_SUPPLIERS_SEQ");
        setCompanyid(ERPSolGlobClassModel.doGetUserCompanyCode());
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            String pkValue=" func_generate_supplier_id('"+getLocationid()+"')";
         String result =
             ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
         populateAttributeAsChanged(SUPPLIERID, result);
        }
        super.doDML(operation, e);
    }
}

