package erpsolaps.erpsolapsmodel.erpsolapsvo;

import erpsolaps.erpsolapsmodel.erpsolapseo.OtherBillDetImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 03 17:55:38 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtherBillDetViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_OTHERBILLDET = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Billid {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getBillid();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setBillid((String) value);
            }
        }
        ,
        Glcode {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getGlcode();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setGlcode((String) value);
            }
        }
        ,
        Costcenter {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getCostcenter();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setCostcenter((String) value);
            }
        }
        ,
        Amount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAmount((BigDecimal) value);
            }
        }
        ,
        GlNarr {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getGlNarr();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setGlNarr((String) value);
            }
        }
        ,
        Createdby {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getCreatedby();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        Modifiedby {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getModifiedby();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        Seqid {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getSeqid();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setSeqid((Integer) value);
            }
        }
        ,
        LocCode {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getLocCode();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setLocCode((String) value);
            }
        }
        ,
        FcurrAmount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getFcurrAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setFcurrAmount((BigDecimal) value);
            }
        }
        ,
        FcurrStAmount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getFcurrStAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setFcurrStAmount((BigDecimal) value);
            }
        }
        ,
        StAmount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getStAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setStAmount((BigDecimal) value);
            }
        }
        ,
        GlNarrRescue2 {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getGlNarrRescue2();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setGlNarrRescue2((String) value);
            }
        }
        ,
        Itemid {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getItemid();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setItemid((String) value);
            }
        }
        ,
        OrderQty {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setOrderQty((BigDecimal) value);
            }
        }
        ,
        ExtraQty {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getExtraQty();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setExtraQty((BigDecimal) value);
            }
        }
        ,
        FcurRate {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getFcurRate();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setFcurRate((BigDecimal) value);
            }
        }
        ,
        BcurRate {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getBcurRate();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setBcurRate((BigDecimal) value);
            }
        }
        ,
        FcurrTotal {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getFcurrTotal();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setFcurrTotal((BigDecimal) value);
            }
        }
        ,
        BcurrTotal {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getBcurrTotal();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setBcurrTotal((BigDecimal) value);
            }
        }
        ,
        MemoBillid {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getMemoBillid();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setMemoBillid((String) value);
            }
        }
        ,
        ExchangeRate {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal) value);
            }
        }
        ,
        PoAmount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getPoAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setPoAmount((BigDecimal) value);
            }
        }
        ,
        Billidseq {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getBillidseq();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setBillidseq((Integer) value);
            }
        }
        ,
        txtGLDescription {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.gettxtGLDescription();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        txtCostCenterName {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.gettxtCostCenterName();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        txtSumAmount {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.gettxtSumAmount();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VWChartOfAccountQVO {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getVWChartOfAccountQVO();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VWCostCenterQVO {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getVWCostCenterQVO();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OtherBillsView {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getOtherBillsView();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccVWChartOfAccountQVO {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getAccVWChartOfAccountQVO();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccVWCostCenterQVO {
            public Object get(OtherBillDetViewRowImpl obj) {
                return obj.getAccVWCostCenterQVO();
            }

            public void put(OtherBillDetViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(OtherBillDetViewRowImpl object);

        public abstract void put(OtherBillDetViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int BILLID = AttributesEnum.Billid.index();
    public static final int GLCODE = AttributesEnum.Glcode.index();
    public static final int COSTCENTER = AttributesEnum.Costcenter.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int GLNARR = AttributesEnum.GlNarr.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int SEQID = AttributesEnum.Seqid.index();
    public static final int LOCCODE = AttributesEnum.LocCode.index();
    public static final int FCURRAMOUNT = AttributesEnum.FcurrAmount.index();
    public static final int FCURRSTAMOUNT = AttributesEnum.FcurrStAmount.index();
    public static final int STAMOUNT = AttributesEnum.StAmount.index();
    public static final int GLNARRRESCUE2 = AttributesEnum.GlNarrRescue2.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int EXTRAQTY = AttributesEnum.ExtraQty.index();
    public static final int FCURRATE = AttributesEnum.FcurRate.index();
    public static final int BCURRATE = AttributesEnum.BcurRate.index();
    public static final int FCURRTOTAL = AttributesEnum.FcurrTotal.index();
    public static final int BCURRTOTAL = AttributesEnum.BcurrTotal.index();
    public static final int MEMOBILLID = AttributesEnum.MemoBillid.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int POAMOUNT = AttributesEnum.PoAmount.index();
    public static final int BILLIDSEQ = AttributesEnum.Billidseq.index();
    public static final int TXTGLDESCRIPTION = AttributesEnum.txtGLDescription.index();
    public static final int TXTCOSTCENTERNAME = AttributesEnum.txtCostCenterName.index();
    public static final int TXTSUMAMOUNT = AttributesEnum.txtSumAmount.index();
    public static final int VWCHARTOFACCOUNTQVO = AttributesEnum.VWChartOfAccountQVO.index();
    public static final int VWCOSTCENTERQVO = AttributesEnum.VWCostCenterQVO.index();
    public static final int OTHERBILLSVIEW = AttributesEnum.OtherBillsView.index();
    public static final int ACCVWCHARTOFACCOUNTQVO = AttributesEnum.AccVWChartOfAccountQVO.index();
    public static final int ACCVWCOSTCENTERQVO = AttributesEnum.AccVWCostCenterQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OtherBillDetViewRowImpl() {
    }

    /**
     * Gets OtherBillDet entity object.
     * @return the OtherBillDet
     */
    public OtherBillDetImpl getOtherBillDet() {
        return (OtherBillDetImpl) getEntity(ENTITY_OTHERBILLDET);
    }

    /**
     * Gets the attribute value for BILLID using the alias name Billid.
     * @return the BILLID
     */
    public String getBillid() {
        return (String) getAttributeInternal(BILLID);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLID using the alias name Billid.
     * @param value value to set the BILLID
     */
    public void setBillid(String value) {
        setAttributeInternal(BILLID, value);
    }

    /**
     * Gets the attribute value for GLCODE using the alias name Glcode.
     * @return the GLCODE
     */
    public String getGlcode() {
        return (String) getAttributeInternal(GLCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLCODE using the alias name Glcode.
     * @param value value to set the GLCODE
     */
    public void setGlcode(String value) {
        setAttributeInternal(GLCODE, value);
    }

    /**
     * Gets the attribute value for COSTCENTER using the alias name Costcenter.
     * @return the COSTCENTER
     */
    public String getCostcenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for COSTCENTER using the alias name Costcenter.
     * @param value value to set the COSTCENTER
     */
    public void setCostcenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for GL_NARR using the alias name GlNarr.
     * @return the GL_NARR
     */
    public String getGlNarr() {
        return (String) getAttributeInternal(GLNARR);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_NARR using the alias name GlNarr.
     * @param value value to set the GL_NARR
     */
    public void setGlNarr(String value) {
        setAttributeInternal(GLNARR, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for SEQID using the alias name Seqid.
     * @return the SEQID
     */
    public Integer getSeqid() {
        return (Integer) getAttributeInternal(SEQID);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQID using the alias name Seqid.
     * @param value value to set the SEQID
     */
    public void setSeqid(Integer value) {
        setAttributeInternal(SEQID, value);
    }

    /**
     * Gets the attribute value for LOC_CODE using the alias name LocCode.
     * @return the LOC_CODE
     */
    public String getLocCode() {
        return (String) getAttributeInternal(LOCCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_CODE using the alias name LocCode.
     * @param value value to set the LOC_CODE
     */
    public void setLocCode(String value) {
        setAttributeInternal(LOCCODE, value);
    }

    /**
     * Gets the attribute value for FCURR_AMOUNT using the alias name FcurrAmount.
     * @return the FCURR_AMOUNT
     */
    public BigDecimal getFcurrAmount() {
        return (BigDecimal) getAttributeInternal(FCURRAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_AMOUNT using the alias name FcurrAmount.
     * @param value value to set the FCURR_AMOUNT
     */
    public void setFcurrAmount(BigDecimal value) {
        setAttributeInternal(FCURRAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_ST_AMOUNT using the alias name FcurrStAmount.
     * @return the FCURR_ST_AMOUNT
     */
    public BigDecimal getFcurrStAmount() {
        return (BigDecimal) getAttributeInternal(FCURRSTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_ST_AMOUNT using the alias name FcurrStAmount.
     * @param value value to set the FCURR_ST_AMOUNT
     */
    public void setFcurrStAmount(BigDecimal value) {
        setAttributeInternal(FCURRSTAMOUNT, value);
    }

    /**
     * Gets the attribute value for ST_AMOUNT using the alias name StAmount.
     * @return the ST_AMOUNT
     */
    public BigDecimal getStAmount() {
        return (BigDecimal) getAttributeInternal(STAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ST_AMOUNT using the alias name StAmount.
     * @param value value to set the ST_AMOUNT
     */
    public void setStAmount(BigDecimal value) {
        setAttributeInternal(STAMOUNT, value);
    }

    /**
     * Gets the attribute value for GL_NARR_RESCUE_2 using the alias name GlNarrRescue2.
     * @return the GL_NARR_RESCUE_2
     */
    public String getGlNarrRescue2() {
        return (String) getAttributeInternal(GLNARRRESCUE2);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_NARR_RESCUE_2 using the alias name GlNarrRescue2.
     * @param value value to set the GL_NARR_RESCUE_2
     */
    public void setGlNarrRescue2(String value) {
        setAttributeInternal(GLNARRRESCUE2, value);
    }

    /**
     * Gets the attribute value for ITEMID using the alias name Itemid.
     * @return the ITEMID
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEMID using the alias name Itemid.
     * @param value value to set the ITEMID
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public BigDecimal getOrderQty() {
        return (BigDecimal) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(BigDecimal value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for EXTRA_QTY using the alias name ExtraQty.
     * @return the EXTRA_QTY
     */
    public BigDecimal getExtraQty() {
        return (BigDecimal) getAttributeInternal(EXTRAQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_QTY using the alias name ExtraQty.
     * @param value value to set the EXTRA_QTY
     */
    public void setExtraQty(BigDecimal value) {
        setAttributeInternal(EXTRAQTY, value);
    }

    /**
     * Gets the attribute value for FCUR_RATE using the alias name FcurRate.
     * @return the FCUR_RATE
     */
    public BigDecimal getFcurRate() {
        return (BigDecimal) getAttributeInternal(FCURRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FCUR_RATE using the alias name FcurRate.
     * @param value value to set the FCUR_RATE
     */
    public void setFcurRate(BigDecimal value) {
        setAttributeInternal(FCURRATE, value);
    }

    /**
     * Gets the attribute value for BCUR_RATE using the alias name BcurRate.
     * @return the BCUR_RATE
     */
    public BigDecimal getBcurRate() {
        return (BigDecimal) getAttributeInternal(BCURRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BCUR_RATE using the alias name BcurRate.
     * @param value value to set the BCUR_RATE
     */
    public void setBcurRate(BigDecimal value) {
        setAttributeInternal(BCURRATE, value);
    }

    /**
     * Gets the attribute value for FCURR_TOTAL using the alias name FcurrTotal.
     * @return the FCURR_TOTAL
     */
    public BigDecimal getFcurrTotal() {
        return (BigDecimal) getAttributeInternal(FCURRTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_TOTAL using the alias name FcurrTotal.
     * @param value value to set the FCURR_TOTAL
     */
    public void setFcurrTotal(BigDecimal value) {
        setAttributeInternal(FCURRTOTAL, value);
    }

    /**
     * Gets the attribute value for BCURR_TOTAL using the alias name BcurrTotal.
     * @return the BCURR_TOTAL
     */
    public BigDecimal getBcurrTotal() {
        return (BigDecimal) getAttributeInternal(BCURRTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for BCURR_TOTAL using the alias name BcurrTotal.
     * @param value value to set the BCURR_TOTAL
     */
    public void setBcurrTotal(BigDecimal value) {
        setAttributeInternal(BCURRTOTAL, value);
    }

    /**
     * Gets the attribute value for MEMO_BILLID using the alias name MemoBillid.
     * @return the MEMO_BILLID
     */
    public String getMemoBillid() {
        return (String) getAttributeInternal(MEMOBILLID);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMO_BILLID using the alias name MemoBillid.
     * @param value value to set the MEMO_BILLID
     */
    public void setMemoBillid(String value) {
        setAttributeInternal(MEMOBILLID, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for PO_AMOUNT using the alias name PoAmount.
     * @return the PO_AMOUNT
     */
    public BigDecimal getPoAmount() {
        return (BigDecimal) getAttributeInternal(POAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_AMOUNT using the alias name PoAmount.
     * @param value value to set the PO_AMOUNT
     */
    public void setPoAmount(BigDecimal value) {
        setAttributeInternal(POAMOUNT, value);
    }

    /**
     * Gets the attribute value for BILLIDSEQ using the alias name Billidseq.
     * @return the BILLIDSEQ
     */
    public Integer getBillidseq() {
        return (Integer) getAttributeInternal(BILLIDSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLIDSEQ using the alias name Billidseq.
     * @param value value to set the BILLIDSEQ
     */
    public void setBillidseq(Integer value) {
        setAttributeInternal(BILLIDSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtGLDescription.
     * @return the txtGLDescription
     */
    public String gettxtGLDescription() {
        return (String) getAttributeInternal(TXTGLDESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCostCenterName.
     * @return the txtCostCenterName
     */
    public String gettxtCostCenterName() {
        return (String) getAttributeInternal(TXTCOSTCENTERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSumAmount.
     * @return the txtSumAmount
     */
    public BigDecimal gettxtSumAmount() {
        return (BigDecimal) getAttributeInternal(TXTSUMAMOUNT);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link VWChartOfAccountQVO.
     */
    public Row getVWChartOfAccountQVO() {
        return (Row) getAttributeInternal(VWCHARTOFACCOUNTQVO);
    }

    /**
     * Sets the master-detail link VWChartOfAccountQVO between this object and <code>value</code>.
     */
    public void setVWChartOfAccountQVO(Row value) {
        setAttributeInternal(VWCHARTOFACCOUNTQVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link VWCostCenterQVO.
     */
    public Row getVWCostCenterQVO() {
        return (Row) getAttributeInternal(VWCOSTCENTERQVO);
    }

    /**
     * Sets the master-detail link VWCostCenterQVO between this object and <code>value</code>.
     */
    public void setVWCostCenterQVO(Row value) {
        setAttributeInternal(VWCOSTCENTERQVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link OtherBillsView.
     */
    public Row getOtherBillsView() {
        return (Row) getAttributeInternal(OTHERBILLSVIEW);
    }

    /**
     * Sets the master-detail link OtherBillsView between this object and <code>value</code>.
     */
    public void setOtherBillsView(Row value) {
        setAttributeInternal(OTHERBILLSVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWChartOfAccountQVO.
     */
    public RowSet getAccVWChartOfAccountQVO() {
        return (RowSet) getAttributeInternal(ACCVWCHARTOFACCOUNTQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWCostCenterQVO.
     */
    public RowSet getAccVWCostCenterQVO() {
        return (RowSet) getAttributeInternal(ACCVWCOSTCENTERQVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getOtherBillsView().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }  
}

