package erpsolaps.erpsolapsmodel.erpsolapsvo;

import erpsolaps.erpsolapsmodel.erpsolapseo.OtherBillsImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 03 17:38:22 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtherBillsViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_OTHERBILLS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Billid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBillid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBillid((String) value);
            }
        }
        ,
        BillDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBillDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBillDate((Date) value);
            }
        }
        ,
        Companyid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getCompanyid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setCompanyid((String) value);
            }
        }
        ,
        Locationid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLocationid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLocationid((String) value);
            }
        }
        ,
        Deptid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getDeptid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setDeptid((String) value);
            }
        }
        ,
        DocTypeId {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getDocTypeId();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setDocTypeId((String) value);
            }
        }
        ,
        Supplierid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getSupplierid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setSupplierid((String) value);
            }
        }
        ,
        Supref {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getSupref();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setSupref((String) value);
            }
        }
        ,
        SuprefDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getSuprefDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setSuprefDate((Date) value);
            }
        }
        ,
        TaxCode {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getTaxCode();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setTaxCode((BigDecimal) value);
            }
        }
        ,
        Remarks {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setRemarks((String) value);
            }
        }
        ,
        Posted {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPosted();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPosted((String) value);
            }
        }
        ,
        Postedby {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPostedby();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPostedby((String) value);
            }
        }
        ,
        PostToInterface {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPostToInterface();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPostToInterface((String) value);
            }
        }
        ,
        TaxFlag {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getTaxFlag();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setTaxFlag((String) value);
            }
        }
        ,
        Createdby {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getCreatedby();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setCreatedby((String) value);
            }
        }
        ,
        CreatedDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date) value);
            }
        }
        ,
        Modifiedby {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getModifiedby();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setModifiedby((String) value);
            }
        }
        ,
        ModifiedDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setModifiedDate((Date) value);
            }
        }
        ,
        ApPosted {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getApPosted();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setApPosted((String) value);
            }
        }
        ,
        GlPosted {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getGlPosted();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setGlPosted((String) value);
            }
        }
        ,
        AuditorCheck {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAuditorCheck();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAuditorCheck((String) value);
            }
        }
        ,
        AuditRemarks {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAuditRemarks();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAuditRemarks((String) value);
            }
        }
        ,
        IsMigrated {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getIsMigrated();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setIsMigrated((String) value);
            }
        }
        ,
        MigratedDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getMigratedDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setMigratedDate((Date) value);
            }
        }
        ,
        ExchangeRate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setExchangeRate((BigDecimal) value);
            }
        }
        ,
        LocCurrcode {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLocCurrcode();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLocCurrcode((String) value);
            }
        }
        ,
        SalesTaxCode {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getSalesTaxCode();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setSalesTaxCode((BigDecimal) value);
            }
        }
        ,
        ProjectId {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getProjectId();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setProjectId((BigDecimal) value);
            }
        }
        ,
        RemarksRescue2 {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getRemarksRescue2();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setRemarksRescue2((String) value);
            }
        }
        ,
        BillType {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBillType();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBillType((String) value);
            }
        }
        ,
        ForwarderSupplierid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getForwarderSupplierid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setForwarderSupplierid((String) value);
            }
        }
        ,
        LcCompleteDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLcCompleteDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLcCompleteDate((Date) value);
            }
        }
        ,
        ImeiFileName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getImeiFileName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setImeiFileName((String) value);
            }
        }
        ,
        InvoiceFileName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getInvoiceFileName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setInvoiceFileName((String) value);
            }
        }
        ,
        BomFileName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBomFileName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBomFileName((String) value);
            }
        }
        ,
        PackFileName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPackFileName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPackFileName((String) value);
            }
        }
        ,
        LcCompleted {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLcCompleted();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLcCompleted((String) value);
            }
        }
        ,
        Poid {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPoid();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPoid((String) value);
            }
        }
        ,
        LcForId {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLcForId();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLcForId((BigDecimal) value);
            }
        }
        ,
        PalletNo {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPalletNo();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPalletNo((BigDecimal) value);
            }
        }
        ,
        CottonQty {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getCottonQty();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setCottonQty((BigDecimal) value);
            }
        }
        ,
        PoSuppRefDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPoSuppRefDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPoSuppRefDate((Date) value);
            }
        }
        ,
        PoSuppRefno {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPoSuppRefno();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPoSuppRefno((String) value);
            }
        }
        ,
        Potype {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPotype();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setPotype((String) value);
            }
        }
        ,
        AuditorCheckBy {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAuditorCheckBy();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAuditorCheckBy((String) value);
            }
        }
        ,
        AuditorCheckDate {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAuditorCheckDate();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAuditorCheckDate((Date) value);
            }
        }
        ,
        AuditorCheckRemarks {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAuditorCheckRemarks();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAuditorCheckRemarks((String) value);
            }
        }
        ,
        Lcno {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getLcno();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setLcno((String) value);
            }
        }
        ,
        Billidseq {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBillidseq();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBillidseq((Integer) value);
            }
        }
        ,
        txtLocationName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.gettxtLocationName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.settxtLocationName((String) value);
            }
        }
        ,
        txtSupplierName {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.gettxtSupplierName();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.settxtSupplierName((String) value);
            }
        }
        ,
        BankRefNo {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getBankRefNo();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setBankRefNo((String) value);
            }
        }
        ,
        OtherBillDetView {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getOtherBillDetView();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AllLocationsView {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAllLocationsView();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PuSuppliersView {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getPuSuppliersView();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccPuSuppliersView {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAccPuSuppliersView();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccAllLocationsView {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAccAllLocationsView();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AccVWYesNoQVO {
            public Object get(OtherBillsViewRowImpl obj) {
                return obj.getAccVWYesNoQVO();
            }

            public void put(OtherBillsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(OtherBillsViewRowImpl object);

        public abstract void put(OtherBillsViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BILLID = AttributesEnum.Billid.index();
    public static final int BILLDATE = AttributesEnum.BillDate.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int SUPREF = AttributesEnum.Supref.index();
    public static final int SUPREFDATE = AttributesEnum.SuprefDate.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int POSTTOINTERFACE = AttributesEnum.PostToInterface.index();
    public static final int TAXFLAG = AttributesEnum.TaxFlag.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int APPOSTED = AttributesEnum.ApPosted.index();
    public static final int GLPOSTED = AttributesEnum.GlPosted.index();
    public static final int AUDITORCHECK = AttributesEnum.AuditorCheck.index();
    public static final int AUDITREMARKS = AttributesEnum.AuditRemarks.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int SALESTAXCODE = AttributesEnum.SalesTaxCode.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int REMARKSRESCUE2 = AttributesEnum.RemarksRescue2.index();
    public static final int BILLTYPE = AttributesEnum.BillType.index();
    public static final int FORWARDERSUPPLIERID = AttributesEnum.ForwarderSupplierid.index();
    public static final int LCCOMPLETEDATE = AttributesEnum.LcCompleteDate.index();
    public static final int IMEIFILENAME = AttributesEnum.ImeiFileName.index();
    public static final int INVOICEFILENAME = AttributesEnum.InvoiceFileName.index();
    public static final int BOMFILENAME = AttributesEnum.BomFileName.index();
    public static final int PACKFILENAME = AttributesEnum.PackFileName.index();
    public static final int LCCOMPLETED = AttributesEnum.LcCompleted.index();
    public static final int POID = AttributesEnum.Poid.index();
    public static final int LCFORID = AttributesEnum.LcForId.index();
    public static final int PALLETNO = AttributesEnum.PalletNo.index();
    public static final int COTTONQTY = AttributesEnum.CottonQty.index();
    public static final int POSUPPREFDATE = AttributesEnum.PoSuppRefDate.index();
    public static final int POSUPPREFNO = AttributesEnum.PoSuppRefno.index();
    public static final int POTYPE = AttributesEnum.Potype.index();
    public static final int AUDITORCHECKBY = AttributesEnum.AuditorCheckBy.index();
    public static final int AUDITORCHECKDATE = AttributesEnum.AuditorCheckDate.index();
    public static final int AUDITORCHECKREMARKS = AttributesEnum.AuditorCheckRemarks.index();
    public static final int LCNO = AttributesEnum.Lcno.index();
    public static final int BILLIDSEQ = AttributesEnum.Billidseq.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int BANKREFNO = AttributesEnum.BankRefNo.index();
    public static final int OTHERBILLDETVIEW = AttributesEnum.OtherBillDetView.index();
    public static final int ALLLOCATIONSVIEW = AttributesEnum.AllLocationsView.index();
    public static final int PUSUPPLIERSVIEW = AttributesEnum.PuSuppliersView.index();
    public static final int ACCPUSUPPLIERSVIEW = AttributesEnum.AccPuSuppliersView.index();
    public static final int ACCALLLOCATIONSVIEW = AttributesEnum.AccAllLocationsView.index();
    public static final int ACCVWYESNOQVO = AttributesEnum.AccVWYesNoQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OtherBillsViewRowImpl() {
    }

    /**
     * Gets OtherBills entity object.
     * @return the OtherBills
     */
    public OtherBillsImpl getOtherBills() {
        return (OtherBillsImpl) getEntity(ENTITY_OTHERBILLS);
    }

    /**
     * Gets the attribute value for BILLID using the alias name Billid.
     * @return the BILLID
     */
    public String getBillid() {
        return (String) getAttributeInternal(BILLID);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLID using the alias name Billid.
     * @param value value to set the BILLID
     */
    public void setBillid(String value) {
        setAttributeInternal(BILLID, value);
    }

    /**
     * Gets the attribute value for BILL_DATE using the alias name BillDate.
     * @return the BILL_DATE
     */
    public Date getBillDate() {
        return (Date) getAttributeInternal(BILLDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_DATE using the alias name BillDate.
     * @param value value to set the BILL_DATE
     */
    public void setBillDate(Date value) {
        setAttributeInternal(BILLDATE, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for DEPTID using the alias name Deptid.
     * @return the DEPTID
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTID using the alias name Deptid.
     * @param value value to set the DEPTID
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @return the DOC_TYPE_ID
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @param value value to set the DOC_TYPE_ID
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for SUPREF using the alias name Supref.
     * @return the SUPREF
     */
    public String getSupref() {
        return (String) getAttributeInternal(SUPREF);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPREF using the alias name Supref.
     * @param value value to set the SUPREF
     */
    public void setSupref(String value) {
        setAttributeInternal(SUPREF, value);
    }

    /**
     * Gets the attribute value for SUPREF_DATE using the alias name SuprefDate.
     * @return the SUPREF_DATE
     */
    public Date getSuprefDate() {
        return (Date) getAttributeInternal(SUPREFDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPREF_DATE using the alias name SuprefDate.
     * @param value value to set the SUPREF_DATE
     */
    public void setSuprefDate(Date value) {
        setAttributeInternal(SUPREFDATE, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public BigDecimal getTaxCode() {
        return (BigDecimal) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(BigDecimal value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for POST_TO_INTERFACE using the alias name PostToInterface.
     * @return the POST_TO_INTERFACE
     */
    public String getPostToInterface() {
        return (String) getAttributeInternal(POSTTOINTERFACE);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_INTERFACE using the alias name PostToInterface.
     * @param value value to set the POST_TO_INTERFACE
     */
    public void setPostToInterface(String value) {
        setAttributeInternal(POSTTOINTERFACE, value);
    }

    /**
     * Gets the attribute value for TAX_FLAG using the alias name TaxFlag.
     * @return the TAX_FLAG
     */
    public String getTaxFlag() {
        return (String) getAttributeInternal(TAXFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_FLAG using the alias name TaxFlag.
     * @param value value to set the TAX_FLAG
     */
    public void setTaxFlag(String value) {
        setAttributeInternal(TAXFLAG, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for AP_POSTED using the alias name ApPosted.
     * @return the AP_POSTED
     */
    public String getApPosted() {
        return (String) getAttributeInternal(APPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for AP_POSTED using the alias name ApPosted.
     * @param value value to set the AP_POSTED
     */
    public void setApPosted(String value) {
        setAttributeInternal(APPOSTED, value);
    }

    /**
     * Gets the attribute value for GL_POSTED using the alias name GlPosted.
     * @return the GL_POSTED
     */
    public String getGlPosted() {
        return (String) getAttributeInternal(GLPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_POSTED using the alias name GlPosted.
     * @param value value to set the GL_POSTED
     */
    public void setGlPosted(String value) {
        setAttributeInternal(GLPOSTED, value);
    }

    /**
     * Gets the attribute value for AUDITOR_CHECK using the alias name AuditorCheck.
     * @return the AUDITOR_CHECK
     */
    public String getAuditorCheck() {
        return (String) getAttributeInternal(AUDITORCHECK);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDITOR_CHECK using the alias name AuditorCheck.
     * @param value value to set the AUDITOR_CHECK
     */
    public void setAuditorCheck(String value) {
        setAttributeInternal(AUDITORCHECK, value);
    }

    /**
     * Gets the attribute value for AUDIT_REMARKS using the alias name AuditRemarks.
     * @return the AUDIT_REMARKS
     */
    public String getAuditRemarks() {
        return (String) getAttributeInternal(AUDITREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDIT_REMARKS using the alias name AuditRemarks.
     * @param value value to set the AUDIT_REMARKS
     */
    public void setAuditRemarks(String value) {
        setAttributeInternal(AUDITREMARKS, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @return the LOC_CURRCODE
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @param value value to set the LOC_CURRCODE
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for SALES_TAX_CODE using the alias name SalesTaxCode.
     * @return the SALES_TAX_CODE
     */
    public BigDecimal getSalesTaxCode() {
        return (BigDecimal) getAttributeInternal(SALESTAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_TAX_CODE using the alias name SalesTaxCode.
     * @param value value to set the SALES_TAX_CODE
     */
    public void setSalesTaxCode(BigDecimal value) {
        setAttributeInternal(SALESTAXCODE, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public BigDecimal getProjectId() {
        return (BigDecimal) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(BigDecimal value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for REMARKS_RESCUE_2 using the alias name RemarksRescue2.
     * @return the REMARKS_RESCUE_2
     */
    public String getRemarksRescue2() {
        return (String) getAttributeInternal(REMARKSRESCUE2);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS_RESCUE_2 using the alias name RemarksRescue2.
     * @param value value to set the REMARKS_RESCUE_2
     */
    public void setRemarksRescue2(String value) {
        setAttributeInternal(REMARKSRESCUE2, value);
    }

    /**
     * Gets the attribute value for BILL_TYPE using the alias name BillType.
     * @return the BILL_TYPE
     */
    public String getBillType() {
        return (String) getAttributeInternal(BILLTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_TYPE using the alias name BillType.
     * @param value value to set the BILL_TYPE
     */
    public void setBillType(String value) {
        setAttributeInternal(BILLTYPE, value);
    }

    /**
     * Gets the attribute value for FORWARDER_SUPPLIERID using the alias name ForwarderSupplierid.
     * @return the FORWARDER_SUPPLIERID
     */
    public String getForwarderSupplierid() {
        return (String) getAttributeInternal(FORWARDERSUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for FORWARDER_SUPPLIERID using the alias name ForwarderSupplierid.
     * @param value value to set the FORWARDER_SUPPLIERID
     */
    public void setForwarderSupplierid(String value) {
        setAttributeInternal(FORWARDERSUPPLIERID, value);
    }

    /**
     * Gets the attribute value for LC_COMPLETE_DATE using the alias name LcCompleteDate.
     * @return the LC_COMPLETE_DATE
     */
    public Date getLcCompleteDate() {
        return (Date) getAttributeInternal(LCCOMPLETEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_COMPLETE_DATE using the alias name LcCompleteDate.
     * @param value value to set the LC_COMPLETE_DATE
     */
    public void setLcCompleteDate(Date value) {
        setAttributeInternal(LCCOMPLETEDATE, value);
    }

    /**
     * Gets the attribute value for IMEI_FILE_NAME using the alias name ImeiFileName.
     * @return the IMEI_FILE_NAME
     */
    public String getImeiFileName() {
        return (String) getAttributeInternal(IMEIFILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for IMEI_FILE_NAME using the alias name ImeiFileName.
     * @param value value to set the IMEI_FILE_NAME
     */
    public void setImeiFileName(String value) {
        setAttributeInternal(IMEIFILENAME, value);
    }

    /**
     * Gets the attribute value for INVOICE_FILE_NAME using the alias name InvoiceFileName.
     * @return the INVOICE_FILE_NAME
     */
    public String getInvoiceFileName() {
        return (String) getAttributeInternal(INVOICEFILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_FILE_NAME using the alias name InvoiceFileName.
     * @param value value to set the INVOICE_FILE_NAME
     */
    public void setInvoiceFileName(String value) {
        setAttributeInternal(INVOICEFILENAME, value);
    }

    /**
     * Gets the attribute value for BOM_FILE_NAME using the alias name BomFileName.
     * @return the BOM_FILE_NAME
     */
    public String getBomFileName() {
        return (String) getAttributeInternal(BOMFILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BOM_FILE_NAME using the alias name BomFileName.
     * @param value value to set the BOM_FILE_NAME
     */
    public void setBomFileName(String value) {
        setAttributeInternal(BOMFILENAME, value);
    }

    /**
     * Gets the attribute value for PACK_FILE_NAME using the alias name PackFileName.
     * @return the PACK_FILE_NAME
     */
    public String getPackFileName() {
        return (String) getAttributeInternal(PACKFILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PACK_FILE_NAME using the alias name PackFileName.
     * @param value value to set the PACK_FILE_NAME
     */
    public void setPackFileName(String value) {
        setAttributeInternal(PACKFILENAME, value);
    }

    /**
     * Gets the attribute value for LC_COMPLETED using the alias name LcCompleted.
     * @return the LC_COMPLETED
     */
    public String getLcCompleted() {
        return (String) getAttributeInternal(LCCOMPLETED);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_COMPLETED using the alias name LcCompleted.
     * @param value value to set the LC_COMPLETED
     */
    public void setLcCompleted(String value) {
        setAttributeInternal(LCCOMPLETED, value);
    }

    /**
     * Gets the attribute value for POID using the alias name Poid.
     * @return the POID
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as attribute value for POID using the alias name Poid.
     * @param value value to set the POID
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for LC_FOR_ID using the alias name LcForId.
     * @return the LC_FOR_ID
     */
    public BigDecimal getLcForId() {
        return (BigDecimal) getAttributeInternal(LCFORID);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_FOR_ID using the alias name LcForId.
     * @param value value to set the LC_FOR_ID
     */
    public void setLcForId(BigDecimal value) {
        setAttributeInternal(LCFORID, value);
    }

    /**
     * Gets the attribute value for PALLET_NO using the alias name PalletNo.
     * @return the PALLET_NO
     */
    public BigDecimal getPalletNo() {
        return (BigDecimal) getAttributeInternal(PALLETNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PALLET_NO using the alias name PalletNo.
     * @param value value to set the PALLET_NO
     */
    public void setPalletNo(BigDecimal value) {
        setAttributeInternal(PALLETNO, value);
    }

    /**
     * Gets the attribute value for COTTON_QTY using the alias name CottonQty.
     * @return the COTTON_QTY
     */
    public BigDecimal getCottonQty() {
        return (BigDecimal) getAttributeInternal(COTTONQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for COTTON_QTY using the alias name CottonQty.
     * @param value value to set the COTTON_QTY
     */
    public void setCottonQty(BigDecimal value) {
        setAttributeInternal(COTTONQTY, value);
    }

    /**
     * Gets the attribute value for PO_SUPP_REF_DATE using the alias name PoSuppRefDate.
     * @return the PO_SUPP_REF_DATE
     */
    public Date getPoSuppRefDate() {
        return (Date) getAttributeInternal(POSUPPREFDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_SUPP_REF_DATE using the alias name PoSuppRefDate.
     * @param value value to set the PO_SUPP_REF_DATE
     */
    public void setPoSuppRefDate(Date value) {
        setAttributeInternal(POSUPPREFDATE, value);
    }

    /**
     * Gets the attribute value for PO_SUPP_REFNO using the alias name PoSuppRefno.
     * @return the PO_SUPP_REFNO
     */
    public String getPoSuppRefno() {
        return (String) getAttributeInternal(POSUPPREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_SUPP_REFNO using the alias name PoSuppRefno.
     * @param value value to set the PO_SUPP_REFNO
     */
    public void setPoSuppRefno(String value) {
        setAttributeInternal(POSUPPREFNO, value);
    }

    /**
     * Gets the attribute value for POTYPE using the alias name Potype.
     * @return the POTYPE
     */
    public String getPotype() {
        return (String) getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for POTYPE using the alias name Potype.
     * @param value value to set the POTYPE
     */
    public void setPotype(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for AUDITOR_CHECK_BY using the alias name AuditorCheckBy.
     * @return the AUDITOR_CHECK_BY
     */
    public String getAuditorCheckBy() {
        return (String) getAttributeInternal(AUDITORCHECKBY);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDITOR_CHECK_BY using the alias name AuditorCheckBy.
     * @param value value to set the AUDITOR_CHECK_BY
     */
    public void setAuditorCheckBy(String value) {
        setAttributeInternal(AUDITORCHECKBY, value);
    }

    /**
     * Gets the attribute value for AUDITOR_CHECK_DATE using the alias name AuditorCheckDate.
     * @return the AUDITOR_CHECK_DATE
     */
    public Date getAuditorCheckDate() {
        return (Date) getAttributeInternal(AUDITORCHECKDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDITOR_CHECK_DATE using the alias name AuditorCheckDate.
     * @param value value to set the AUDITOR_CHECK_DATE
     */
    public void setAuditorCheckDate(Date value) {
        setAttributeInternal(AUDITORCHECKDATE, value);
    }

    /**
     * Gets the attribute value for AUDITOR_CHECK_REMARKS using the alias name AuditorCheckRemarks.
     * @return the AUDITOR_CHECK_REMARKS
     */
    public String getAuditorCheckRemarks() {
        return (String) getAttributeInternal(AUDITORCHECKREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDITOR_CHECK_REMARKS using the alias name AuditorCheckRemarks.
     * @param value value to set the AUDITOR_CHECK_REMARKS
     */
    public void setAuditorCheckRemarks(String value) {
        setAttributeInternal(AUDITORCHECKREMARKS, value);
    }

    /**
     * Gets the attribute value for LCNO using the alias name Lcno.
     * @return the LCNO
     */
    public String getLcno() {
        return (String) getAttributeInternal(LCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LCNO using the alias name Lcno.
     * @param value value to set the LCNO
     */
    public void setLcno(String value) {
        setAttributeInternal(LCNO, value);
    }

    /**
     * Gets the attribute value for BILLIDSEQ using the alias name Billidseq.
     * @return the BILLIDSEQ
     */
    public Integer getBillidseq() {
        return (Integer) getAttributeInternal(BILLIDSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BILLIDSEQ using the alias name Billidseq.
     * @param value value to set the BILLIDSEQ
     */
    public void setBillidseq(Integer value) {
        setAttributeInternal(BILLIDSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for BANK_REF_NO using the alias name BankRefNo.
     * @return the BANK_REF_NO
     */
    public String getBankRefNo() {
        return (String) getAttributeInternal(BANKREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_REF_NO using the alias name BankRefNo.
     * @param value value to set the BANK_REF_NO
     */
    public void setBankRefNo(String value) {
        setAttributeInternal(BANKREFNO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OtherBillDetView.
     */
    public RowIterator getOtherBillDetView() {
        return (RowIterator) getAttributeInternal(OTHERBILLDETVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllLocationsView.
     */
    public Row getAllLocationsView() {
        return (Row) getAttributeInternal(ALLLOCATIONSVIEW);
    }

    /**
     * Sets the master-detail link AllLocationsView between this object and <code>value</code>.
     */
    public void setAllLocationsView(Row value) {
        setAttributeInternal(ALLLOCATIONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuSuppliersView.
     */
    public Row getPuSuppliersView() {
        return (Row) getAttributeInternal(PUSUPPLIERSVIEW);
    }

    /**
     * Sets the master-detail link PuSuppliersView between this object and <code>value</code>.
     */
    public void setPuSuppliersView(Row value) {
        setAttributeInternal(PUSUPPLIERSVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPuSuppliersView.
     */
    public RowSet getAccPuSuppliersView() {
        return (RowSet) getAttributeInternal(ACCPUSUPPLIERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsView.
     */
    public RowSet getAccAllLocationsView() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWYesNoQVO.
     */
    public RowSet getAccVWYesNoQVO() {
        return (RowSet) getAttributeInternal(ACCVWYESNOQVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

