package erpsolaps.erpsolapsmodel.erpsolapsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 30 10:05:26 PKT 2022
// ---------------------------------------------------------------------
public interface NoteMasterView extends ViewObject {
    void doSuperviseNote();
}

