package erpsolaps.erpsolapsmodel.erpsolapsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 03 16:59:11 PKT 2022
// ---------------------------------------------------------------------
public interface OtherBillsView extends ViewObject {
    void doSuperviseOtherBills();
}

