package erpsolaps.erpsolapsmodel.erpsolapsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 07 23:32:52 PKT 2022
// ---------------------------------------------------------------------
public interface PaymentMasterView extends ViewObject {
    void doSupervisePayments();
}

