package erpsolaps.erpsolapsmodel.erpsolapsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 15 17:04:58 PKT 2022
// ---------------------------------------------------------------------
public interface VWPayPayableReportQVO extends ViewObject {
    void doSetPayableReportDefaults();

    void doSetERPSolAPDocumentUnsubmit();
}

