package erpsolaps.erpsolapsmodel.erpsolapsqvo;

import erpsolaps.erpsolapsmodel.erpsolapsqvo.common.VWPayPayableReportQVO;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 15 17:02:28 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VWPayPayableReportQVOImpl extends ViewObjectImpl implements VWPayPayableReportQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public VWPayPayableReportQVOImpl() {
    }
    
    public void doSetPayableReportDefaults() {
        ViewObject vo=getApplicationModule().findViewObject("QvoLAPSoc");
              if (vo!=null) {
                  vo.remove();
             }
              vo=getApplicationModule().createViewObjectFromQueryStmt("QvoLImsoc", "select locationid, location_description from all_locations where locationid='"+ERPSolGlobClassModel.doGetUserLocationCode()+"'");
              vo.executeQuery();
              this.first().setAttribute("Locationid", vo.first().getAttribute(0));
              this.first().setAttribute("txtLocationName", vo.first().getAttribute(1));
              this.first().setAttribute("txtCompanyId", ERPSolGlobClassModel.doGetUserCompanyCode());
              this.first().setAttribute("txtFromDate", this.first().getAttribute("txtDefaultDate"));
              this.first().setAttribute("txtToDate", this.first().getAttribute("txtDefaultDate"));
              vo.remove();
    }
    public void doSetERPSolAPDocumentUnsubmit() {
        CallableStatement cs=this.getDBTransaction().createCallableStatement("begin ?:=pkg_payable.func_unsubmit_ap_document('"+this.first().getAttribute("txtDocTypeId")+"','"+this.first().getAttribute("txtDocumentId")+"','"+ERPSolGlobClassModel.doGetUserCode()+"'); END;", 1);
        System.out.println("begin ?:=pkg_payable.func_unsubmit_ap_document('"+this.first().getAttribute("txtDocTypeId")+"','"+this.first().getAttribute("txtDocumentId")+"','"+ERPSolGlobClassModel.doGetUserCode()+"'); END;");
        try {
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.executeUpdate();
            
    //            if (!cs.getString(1).equals("ERPSOLSUCCESS")) {
                JboException jboex=new JboException(cs.getString(1));
                jboex.setSeverity(JboException.SEVERITY_WARNING); 
                throw new JboException(jboex);
    //           }
    //            this.getDBTransaction().commit();
        } catch (SQLException e) {
        //            this.getCurrentRow().setAttribute("Submit", "N");
            this.getDBTransaction().commit();
            System.out.println(e.getMessage()+ "this is message");
            throw new JboException("Unable to supervise ");
        }
        finally{
            try {
                cs.close();
                System.out.println("closing----");
            } catch (SQLException e) {
            }
        }

        
    }
}

